### ISSUE TITLE
Multi Currency

### ISSUE THREAD

**Issue by ysn** [facebookincubator/Facebook-For-OpenCart#110]
No multi currency support..  
So I can't use the module.
Will you add multiple currencies?

**Comment by ysn** [comment]
db: after price, currency_id.

system/library/cart/currency.php:
search: $this->currencies[$result['code']] = array(
after: 'currency_id'   => $result['currency_id'],
search: public function getSymbolLeft($currency) {
before: 
public function getId($currency) {
		if (isset($this->currencies[$currency])) {
			return $this->currencies[$currency]['currency_id'];
		} else {
			return 0;
		}
	}

search: public function has($currency) {
before: 
public function getCodeOrDefault($id=false) {
		foreach($this->currencies as $code=>$currency) {
			if($id === $currency['currency_id']) {
				return $code;
			}		
		}		
		return $this->config->get('config_currency');	
	}

------------

code logic this way..

The default currency in your code mixed my head.. i could not fix it..
------

and special price is not show :S

**Comment by shue249** [comment]
@ysn Thank you for your feedback. Can you explain more on multi-currency for us to better understand your request. If you can provide screenshots, that will help us understand better.

At the moment, our plugin is supporting the firing of pixels with the right currency on the web store. Pls see the below screenshots for an example.
![image](https://user-images.githubusercontent.com/11957585/53280392-7fa7e180-3754-11e9-9056-ca2274d39ad5.png)
![image](https://user-images.githubusercontent.com/11957585/53280398-9cdcb000-3754-11e9-98ea-4903c560de99.png)
![image](https://user-images.githubusercontent.com/11957585/53280423-f6dd7580-3754-11e9-9db3-0dec698a8486.png)
![image](https://user-images.githubusercontent.com/11957585/53280446-2b513180-3755-11e9-811c-40c364bce971.png)
![image](https://user-images.githubusercontent.com/11957585/53280454-5b98d000-3755-11e9-850a-f4af5d06fb15.png)

**Comment by ysn** [comment]
hi,
u must use the currency library.  system/library/cart/currency.
not necessary for default currency.

example, extension/feed/google_base:

```
$currencies = array(
							'USD',
							'EUR',
							'TRY'
						);

						if (in_array($this->session->data['currency'], $currencies)) {
							$currency_code = $this->session->data['currency'];
							$currency_value = $this->currency->getValue($this->session->data['currency']);
						} else {
							$currency_code = 'TRY';
							$currency_value = $this->currency->getValue('TRY');
						}

						if ((float)$product['special']) {
							$output .= '  <g:price>' .  $this->currency->format($this->tax->calculate($product['special'], $product['tax_class_id']), $currency_code, $currency_value, false) . '</g:price>';
						} else {
							$output .= '  <g:price>' . $this->currency->format($this->tax->calculate($product['price'], $product['tax_class_id']), $currency_code, $currency_value, false) . '</g:price>';
						}
```
`$this->currency->format`   
takes care of all this problem..

Sorry for my english. did i tell?

**Comment by ysn** [comment]
example:

catalog/controller/product/product.php

```
if ($this->customer->isLogged() || !$this->config->get('config_customer_price')) {
				$data['price'] = $this->currency->format($this->tax->calculate($product_info['price'], $product_info['tax_class_id'], $this->config->get('config_tax')), $this->session->data['currency']);
			} else {
				$data['price'] = false;
			}
```

if you use this way there is no problem..

**Comment by shue249** [comment]
@ysn Thank you for the feedback.

Our plugin setup the Facebook pixel and sync the OpenCart products to Facebook catalog.
The earlier example and screenshots we shared are for the Facebook pixel.

For the Facebook catalog, we are only supporting for a single currency and hence we are using the default currency and price of the OpenCart products.

We will mark this request as an enhancement on how to support for multi currency and prices for the Facebook catalog.

**Comment by yao-tx** [comment]
Hi @ysn 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the FBE plugin (version 4.0.0 and above) supports multi-currency for firing of Facebook Pixels. Instead of using the default store currency when sending Pixels, it now uses the currency set by the customer (i.e. `$this->session->data['currency']`). 

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
