### ISSUE TITLE
Facebook-for-opencart Fatal error Invalid opcode 153/1/8

### ISSUE THREAD

**Issue by lipmycar** [facebookincubator/Facebook-For-OpenCart#12]
Hello support team,
After extension installation this fatal error came up:
Fatal error: Invalid opcode 153/1/8. in /home/lipmycar/public_html/admin/controller/extension/facebookadsextension.php on line 421
Now I am not able to log in to my admin panel and there are some errors on the website.
My Opencart version is 2.0.3.1. I have installed Facebook for OpenCart v2.0.1
I really need your help on this.
Thanks

**Comment by shue249** [comment]
Hi! You can remove the plugin by accessing this URL on your admin panel - index.php?route=extension/modification. This will allow you to access back your admin panel.

Do you have any eaccelerator installed on your OpenCart. If so, can you share the version of the eaccalerator and your PHP version? 

Let me know if this makes sense.

**Comment by lipmycar** [comment]
Thank you!
I've managed to uninstall the extension, but another problem appeared. There is an error in modules section in admin panel : "Page Not Found"
I haven't installed any accelerators on my Opencart. I checked in the Cpanel, my PHP version is 5.6.30

**Comment by lipmycar** [comment]
Ok, I fixed the problem with modules section after I deleted admin/controller/extension/module. I still would like to use the extension. Any ideas?
THank you,
Nikolay

**Comment by shue249** [comment]
Thank you for your feedback! This is very interesting to us, as this is also the first time we are seeing this problem. We can continue to take a look, but pls let us know if you have any thoughts to this.

**Comment by shue249** [comment]
Just a quick thought, are you running any opcode cache? https://forum.joomla.org/viewtopic.php?t=848554

**Comment by lipmycar** [comment]
My mistake. PHP version was 5.3. I change it to 5.6 and succesfully installed the extension without this opcode fatal error, but again modules in admin panel are missing.

**Comment by shue249** [comment]
Thanks for your feedback! Can you share a screenshot on how the modules in admin panel missing looks like, for us to better understand this.

**Comment by lipmycar** [comment]
I really appreciate your help! This is the screenshot that shows the modules issue:
![clipboard03](https://user-images.githubusercontent.com/40515131/41807886-2cf153fe-76de-11e8-927a-9656c76bdbff.png)

**Comment by lipmycar** [comment]
Previously I deleted admin/controller/extension/module and the file in it created by the extension and everything was fine with modules after that.  After your advices I have succfully installed the extension and of course the same foulder and file are created again :)

**Comment by shue249** [comment]
Thanks for the feedback. So want to understand this better. Is your modules page back to normal now? Or are you still facing the same problem/

**Comment by lipmycar** [comment]
If i delete folder admin/controller/extension/module and the file in it my modules go back to normal. Now I am facing the problem (shown in the screenshot) becase I've successfully installed the facebook extension and this folder is created again.
Thank you

**Comment by shue249** [comment]
Thank you for your feedback and we really appreciate your patience! We will deep dive into this and inform you soonest.

Probably you have already done this. Pls uninstall the plugin first while we work on this.

**Comment by shue249** [comment]
@lipmycar Thank you for your feedback. We will check this out and get back to you soonest!

**Comment by lipmycar** [comment]
I searched over the internet and couldn't find any solution that works. If I delete the above mentioned folder the facebook extension stops working. I really hope you will find a way to fix this.
Thank you!

**Comment by shue249** [comment]
Thank you for your feedback! Let us work on this and get back to you soonest!

**Comment by dalibordim** [comment]
i got the exact same problems with the folder admin/controller/extension/module, and after removing the folder i got the same error messages on the admin page. Seams that only OC 2.0.3.1 has this problem because I've tested the extension on 2.3 and it works perfectly

**Comment by shue249** [comment]
@lipmycar , @dalibordim Thank you again for your comments. We are working on a fix now. We will keep you updated the soonest when we have the fix ready for Opencart v2.0.3.1

**Comment by amplexus** [comment]
Hi,

I had the same problem in my 2.0.3.1 installation. The way I fixed this issue was to:
1. rename admin/controller/extension/module/facebookadsextension_installer.php to admin/controller/extension/fbinstaller/facebookadsextension_installer.php
2. rename admin/language/en-gb/extension/module/facebookadsextension_installer.php to cnut/language/en-gb/extension/fbinstaller/facebookadsextension_installer.php
3. edit the contents of admin/controller/extension/facebookadsextension.php to point to the new location of the above files

Cheers,
Craig

**Comment by dalibordim** [comment]
I noticed a different issue. The installation went ok and i got a new option in the admin menu on the side but after setting everything up the problem now is that the pixel is not showing any data in the Facebook Pixel Helper.

**Comment by shue249** [comment]
@dalibordim Thank you for your feedback! Can I ask you to open a separate ticket so that we are not diluting the problem for this issue. At the same time, can I ask for your website URL.

**Comment by shue249** [comment]
We have released the new version v2.0.3 which addressed this issue. We will be closing off this ticket, but feel free to open it if you have any further questions.

Facebook Ads Extension
Latest version: 2.0.3

Change log
2.0.3 - 7 August 2018
* Improves on the robustness of firing the Facebook pixels by using preactions (OpenCart v2.2.0.0 and higher) or tapping into the maintenance controller (lower than OpenCart v.2.2.0.0). This replaces almost all of the code-injection of Facebook pixel on the webstore front (files in catalog folder)
* Changes the pixel event Lead to Contact when users reach out to your store via the Contact Us form
* Added in a new pixel event, Subscribe, when users subscribe/unsubscribe to Newsletter
* Fixes the error for conflicting admin/controller/extension/module folder for OpenCart v2.0.3.1
* Fixes the console error for GDPR cookie consent due to outdated library files. Credits to Craig Jackson, @amplexus. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/19
* Fixes a warning due to usage of the dirname command
