### ISSUE TITLE
FB Pixel v2.1.5 No Pixel On Website - OC2.3.0.2

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#128]
I recently updated the fb extension to the latest version 2.1.5.

The catalogue seems to work but I'm not getting any pixel events and the pixel doesnt seem to even be on my site anymore?

Im on Opencart 2.3.0.2

**Comment by ryanstacey** [comment]
So there is no pixel firing on v2.1.5 or on v2.1.4.
So I have went back and installed v2.1.3 until this is fixed.

**Comment by shue249** [comment]
@ryanstacey Thank you for the feedback.

Will you be able to help us install back the v2.1.5 and share with us the modifications log, so that we can troubleshoot better. You can install back v2.1.3 after this.

![image](https://user-images.githubusercontent.com/11957585/54570446-74756800-4a19-11e9-91db-179167d08442.png)

**Comment by ryanstacey** [comment]
[FB-Github-v2.1.5-Log.txt](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2982575/FB-Github-v2.1.5-Log.txt)

**Comment by shue249** [comment]
@ryanstacey Thank you for the log file, we are still checking on this and trying to repo this on our side. We will update you soonest when we have any findings.

**Comment by shue249** [comment]
@ryanstacey We think we have found the root of the problem. Will you be able to share a file with us so that we can double confirm our hypothesis. The file is /system/engine/front.php on your webserver.

![image](https://user-images.githubusercontent.com/11957585/55445157-bac8dc00-556e-11e9-8828-36e85ecd5890.png)

**Comment by shue249** [comment]
@ryanstacey  , we have just released a version 2.1.6 which will we hope to solve the pixel firing issue on your system.

Can you upgrade the plugin to the latest version and see if all the pages are now firing pixel, eg product details page, product category, shopping cart, check out and payment. Pls let us know the status on your website.

**Comment by shue249** [comment]
@ryanstacey. We will be closing out this ticket. Feel free to reach to us if you have any further questions.
