### ISSUE TITLE
problem with uplouding the catalog from e-shop to Facebook ads extension

### ISSUE THREAD

**Issue by crossbodycom80** [facebookincubator/Facebook-For-OpenCart#141]
Hello, I try to implement the catalog to Facebook ads extension but it gives me a message -

There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.

after the steps, it gives me another message:

Connection failed
Check that you're logged into your store. You can close this window and reopen the plugin from inside your store's admin panel.
What i have to do?

**Comment by shue249** [comment]
@crossbodycom80 Can you check if the Facebook login on your browser has access to the Facebook Page that you have used in the setup? 

You are seeing "Connection failed
Check that you're logged into your store. You can close this window and reopen the plugin from inside your store's admin panel." because the current browser Facebook login does not have access to the Facebook page used in the Facebook Ads Extension setup.

**Comment by shue249** [comment]
@crossbodycom80 We will be closing out this ticket. Pls feel free to reach to us if you have any further questions.
