### ISSUE TITLE
Handling of pre-order products

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#153]
90% of my website order are pre-order items. 
Therefore I will set items quantity in Opencart as 'zero' for pre-order items and opencart will display as "Pre-order" when it is out of stock.
However, facebook catalog will show item all "out of stock" and disable the link to my website on the Facebook shop tab.
May I know how to solve this problem?

**Comment by shue249** [comment]
@i3kevin Thank you for your feedback. This is an interesting use case. Let us look into this and see how we can put in this enhancement. We will update you soonest when we have any updates.

**Comment by i3kevin** [comment]
When I change the product setting: subtract stock -> "NO", will this solve the problem?
Then facebook shop will always display "in stock" even I have 'zero' quantity in the backend?

**Comment by shue249** [comment]
@i3kevin That is correct - putting as subtract stock -> No will always display as stock available on Facebook page shop. If this works for you, you can use this method first.

**Comment by i3kevin** [comment]
Is there any update on this issue?

**Comment by shue249** [comment]
@i3kevin We are working on this enhancement now. We plan to roll out some other fixes together. Pls do bear with us and we will update you soonest when ready.

**Comment by shue249** [comment]
@i3kevin We have released a new version 2.1.9 which supports the pre order stock status. You will need to edit-save the products so that the status is reflected on Facebook catalog.

This is the logic that we are using:
Added mapping for predefined OpenCart product status into Facebook catalog availability. Note that Facebook Page Shop only shows "Not available" for out of stock and Checkout to website" for all other status. The logic is as follow:

- OpenCart Preorder = Facebook Preorder
- OpenCart 2-3 days = Facebook In stock
- OpenCart Out of stock = Facebook Out of stock
- OpenCart In stock, subtract Yes, Zero quantity = Facebook Out of stock
- OpenCart In stock, subtract Yes, 1 or more quantity = Facebook In stock
- OpenCart In stock, subtract No (regardless of quantity) = Facebook In stock

We will be closing out the ticket, but pls feel free to reach to us if you have any further questions.
