### ISSUE TITLE
Journal3 is not conforming to Opencart default implementation; resulting in not directing to checkout automatically on product listing pages

### ISSUE THREAD

**Issue by bloodey** [facebookincubator/Facebook-For-OpenCart#155]
Firstly thanks for this great extension.
I'm using latest version of FFO (2.1.6) with Journal 3 (www.sarvonni.com)
Normally, my products have buy now (quick buy) function which automatically adds product to cart and then redirect you to checkout page. But after installing this extension this function doesnt work anymore. I mean if you click buy now (Heman al in my site) button products goes to cart but it stops there. I contact with developers of my theme but they said its not their problem should contact with extension developer.
How can i fix this issue can you guide me please?
Regards.

**Comment by shue249** [comment]
@bloodey This is what we observed.
1. The (Helman al) button on the product details page work as expected; it directs to checkout page.
![image](https://user-images.githubusercontent.com/11957585/56857313-7a5a5380-699e-11e9-8a23-8913060b063f.png)

2. The (Helman al) button on the product listing page does not work as expected. Upon further investigation, the reason is because Journal 3 is not using the OpenCart default signature of cart.add() method. Our plugin conforms to the OpenCart default signature. This is the reason why the button click is not redirecting to the checkout page. 

Unfortunately, this is not something we can fix on our end, as we are already conforming to OpenCart's standard. You may like feedback this to Journal 3 developers.

![image](https://user-images.githubusercontent.com/11957585/56857331-aece0f80-699e-11e9-877a-caf687629262.png)

![image](https://user-images.githubusercontent.com/11957585/56857359-108e7980-699f-11e9-9964-704f954df98e.png)

![image](https://user-images.githubusercontent.com/11957585/56857376-49c6e980-699f-11e9-973e-99a78c87daac.png)

**Comment by shue249** [comment]
@bloodey We will be closing out this ticket, feel free to reach to us if you have any further questions.

**Comment by denpro433** [comment]
did u fixed

**Comment by bloodey** [comment]
@denpro433 
Yes i fixed it. Open catalog/view/javascript/facebook/facebook_pixel_x_x_x.js

Replace 

```
    if (typeof cart !== 'undefined') {
      var oldCartAdd = cart.add;
      cart.add = function(productID, quantity) {
        fireProductInfoEvent('AddToCart', productID, quantity);
        oldCartAdd.apply(oldCartAdd, [productID, quantity]);
      };
```

With

```
    if (typeof cart !== 'undefined') {
      var oldCartAdd = cart.add;
      cart.add = function(productID, quantity, quickbuy) {
		fireProductInfoEvent('AddToCart', productID, quantity);
		oldCartAdd.apply(oldCartAdd, [productID, quantity, quickbuy]);
     };
```
Thats all. I didnt check the latest facebook extension i was using 2.1.10 version maybe they modified the original file but the idea is same you need to modify it for Journal 3. And dont forget to replace it with every facebook extension update.
Regards.
