### ISSUE TITLE
[OpenCart 2.0.3.1] - facebookadsextension_installer.php makes admin -> extensions -> modules menu "not found"

### ISSUE THREAD

**Issue by amplexus** [facebookincubator/Facebook-For-OpenCart#17]
Hi,

I have OpenCart 2.0.3.1.

When I installed your module, I found that clicking on the Admin --> Extensions --> Modules menu option displayed "not found" when I clicked on it.

I discovered that the root cause was the addition of a "module" directory:
* admin/controller/extension/module/facebookadsextension_installer.php

When I removed the admin/controller/extension/module directory, the Modules menu option started working again. Note that the problem is the "module" directory, not the facebookadsextension_installer.php file in that directory. The presence of the "module" directory seemed to confuse the admin interface.

If you change the name of the module directory, then the problem goes away.

Thanks,
Craig

**Comment by amplexus** [comment]
Thanks shue249, I thought that #12 was an "opcode error" problem, I should have read all the comments :)

**Comment by shue249** [comment]
@amplexus No apologies needed, I will have done the same if I were you. And thank you so much for offering the suggestions for the fix in the other thread :)

**Comment by shue249** [comment]
We have released the new version v2.0.3 which addressed this issue. We will be closing off this ticket, but feel free to open it if you have any further questions.

Facebook Ads Extension
Latest version: 2.0.3

Change log
2.0.3 - 7 August 2018
* Improves on the robustness of firing the Facebook pixels by using preactions (OpenCart v2.2.0.0 and higher) or tapping into the maintenance controller (lower than OpenCart v.2.2.0.0). This replaces almost all of the code-injection of Facebook pixel on the webstore front (files in catalog folder)
* Changes the pixel event Lead to Contact when users reach out to your store via the Contact Us form
* Added in a new pixel event, Subscribe, when users subscribe/unsubscribe to Newsletter
* Fixes the error for conflicting admin/controller/extension/module folder for OpenCart v2.0.3.1
* Fixes the console error for GDPR cookie consent due to outdated library files. Credits to Craig Jackson, @amplexus. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/19
* Fixes a warning due to usage of the dirname command
