### ISSUE TITLE
2.3.0.2 with journal 2 pixel is not firing, and missing products in the Facebook catalog

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#173]
Two main problems here: 
1. Pixel cannot fired normally 
2. Product catalog are not fully syned.

I am using OC 2.3.0.2 with Journal 2.
Things were good when I was using Plugin Version: 2.1.3.
all products can be uploaded to catalog and pixel fired normally.

However, Facebook pixel cannot be fired when I updated to 2.1.5 and part of the products are missing while product catalog is being updated. 
Same situation when i updated to 2.1.6 and 2.1.7. problem still not fixed.
Just tried On the version 2.1.8 today, and the pixel are still not firing normally. 

Now, some of the products are syned but part of them are not syned since version 2.1.5. Already tried to request "Fetch again".
Opencart shows 'There are 1184 Products in your inventory'.
However in catalog, there is only 981 products.

I will need the product catalog to be updated and pixel (add to cart) can be fired to create campaign for Facebook Remarketing.
Can you please help me to solve this problem? Thanks a lot!!!

I now installed back to version v2.1.3 to prevent pixel data lost until the firing problem is solved.
I will provide the log file below.

An extra question, how will facebook detemine a Content ID or product ID while uploading to the Facebook catalog?
If I disable some products and upload new products on opencart, will there be a duplicate/reuse Content ID? I am afraid there will be mix up while there is a re-marketing campaign on Facebook. (People are not seeing the according products on ads)

P.S. when I installed v2.1.8 and do click on "Resync Products to Facebook".
The following error ocurred:

Error 524 
Ray ID: 4d7f3998389b3341 • 2019-05-16 17:57:31 UTC
A timeout occurred

**Comment by i3kevin** [comment]
[2019-05-17_02-03-28_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3188626/2019-05-17_02-03-28_facebook_ads_extension.log)

I cannot paste the log here since it is too long and exceeds the characters limit.

**Comment by shue249** [comment]
@i3kevin Again, I apologise for the sub-optimal experience with the plugin.

Based on your feedback here and this other thread https://github.com/facebookincubator/Facebook-For-OpenCart/issues/174, our suggestions will be as follow:

1. Since you have already deleted away the existing Facebook Ads Extension settings, we will suggest for you to use the new catalog. As that new catalog will have the latest updated products, it will solve the problem missing products.

2. For the pixel issue, I feel that your problem could be the same as this user https://github.com/facebookincubator/Facebook-For-OpenCart/issues/116. Can you share with us here a copy of this file on your webserver for us to determine if the problem is the same. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/116#issuecomment-488556429

3. For the content ID/product ID, we are using the unique ID generated by Opencart (Opencart uses the database to generate the unique ID). Because these ID are uniquely generately, there will be no issues with duplicates/reuse. For example, if you choose to create 2 products with the exact same details (name, descriptions etc), Opencart will automatically generate 2 different unique IDs for these 2 products and we are using those unique IDs as the content id/product id.

![image](https://user-images.githubusercontent.com/11957585/57963581-97a88f00-7958-11e9-9804-35371933bac0.png)

**Comment by i3kevin** [comment]
**1. Pixel cannot fired normally.**

I am using SEO plugin to change the URL for product and category pages. But it works fine on 2.1.3 version. And catalog sync works well on 2.1.3. I use vqmod as well.

**Files are here:**
 /system/engine/front.php
[front.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3195490/front.zip)

/system/storage/modification/system/engine/front.php
[front.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3195492/front.zip)

**2. Product catalog are not fully syned.**
![image](https://user-images.githubusercontent.com/45218158/57986718-380ec880-7aab-11e9-945e-bc7251210b61.png)
In opencart facebook extension, there are 1193 products and last update was 3 days ago. (while I mentioned I deleted the whole setting 3 days ago and also the old catalog was also deleted) I tried to "Fetch Now" or "Resync Products to Facebook", both does not work. Last update date still same and this will lead to my ad campaign cannot display dynamic ads to users due to missing catalog products.

![image](https://user-images.githubusercontent.com/45218158/57986714-1e6d8100-7aab-11e9-97eb-5e3f2a12bb42.png)
In Facebook catalog, it only shows 982 products, which means 211 products are missing.

**3. Catalog deleted problem**
Does that mean for the existing ads campaign which used the old catalog (which has been deleted now), I have to shutdown all of them and create a new ad campaign instead? I created some new ads but the cost per engagement were like 3x or 4x higher than the old ones. Is there a way in the Ads Manager that I can use the old ads campaign (including all data that already collected) and just point back to the new catalog? Really frustrating here since the ad cost are so high due to the loss of the old catalog.

**Comment by shue249** [comment]
@i3kevin Thanks for the feedback.

1. For the pixel problem, we found the problem and we are working on a fix to solve this.
![image](https://user-images.githubusercontent.com/11957585/58059376-29a1d900-7b9f-11e9-84d0-f6c634710672.png)

2. For the catalog problem where products are not in synced - we are looking at a different approach to solve this problem.

3. Can you wait for 1 week for the new catalog to collect sufficient signals before running ads. This will help you in the high initial costs of the ads. We can bring this feedback to our product teams to see if we can improve on this.

**Comment by shue249** [comment]
@i3kevin We have released a new version 2.1.9, to address the issue for the pixel firing. Can you try out the new version and let us know if the pixel is now firing correctly on your website.

**Comment by i3kevin** [comment]
How about the product syn issue?

**Comment by i3kevin** [comment]
is that possible I can create a feed file and upload it manually to keep my product up to date?

![Screenshot_122](https://user-images.githubusercontent.com/45218158/58740632-0222fa00-8444-11e9-8d55-a4e14df9eeab.jpg)

**Comment by i3kevin** [comment]
> @i3kevin We have released a new version 2.1.9, to address the issue for the pixel firing. Can you try out the new version and let us know if the pixel is now firing correctly on your website.

Just installed the new version 2.1.9. The pixel is firing well now. Thanks for your help!
However, if I remove the d_event_manager.xml in the future (which you mentioned above that re-wrote opencart default code), does this affect the pixel firing on the version of 2.1.9?

On the other hand, a lot of new products are still not sync to Facebook catalog and I cannot create re-marketing ads for users. Hopefully this can be solved soon.

**Comment by i3kevin** [comment]
Just tried a FORCE "Resync Products to Facebook" on the extension.
Although there is an error 524 and admin panel was down for 15 mins, it seems like all the product are successfully synced to Facebook catalog. 

Do you know where I can see my exact number of products in the catalog?
I want to compare with the numbers in Opencart to see if it is fully synced.
![Screenshot_125](https://user-images.githubusercontent.com/45218158/58754598-6efec880-8506-11e9-914a-eaeb6be30dc1.jpg)

**Comment by shue249** [comment]
@i3kevin Thanks for the feedback.

1. Yes, the downtime is expected when using the Resync products function. We are now looking on this to improve the performance. You should not need to manually create any feed file on your own as the plugin is expected to be able to handle all product syncs

2. Removal of the d_event_manager.xml should not affect the pixel firing. Our changes is to try to make our plugin as robust as possible

3. Currently, we do not show the exact product number if the number of products is too large. I can give this feedback to our product team if they can improve on this.

In the meantime, as I see that this problem is solved on your side, we will close out this ticket. Feel free to reach to us if you have any further questions.
