### ISSUE TITLE
Messenger plugin popping up

### ISSUE THREAD

**Issue by guilhermeojs** [facebookincubator/Facebook-For-OpenCart#193]
Hi there lads!

First of all, congratulations for all the good work y'all have been doing.

Is it possible to disable the messenger pop-up message on mobile? I've noticed that it is quite annoying that the setup message pops up and takes up most of the screen space left on the phone.

It would be awesome to disable it for mobile only, since on desktop it doesn't ruin the UX.

That message is something that ruins user experience while you are using your phone on the wbesite.

**Comment by shue249** [comment]
@guilhermeojs Thanks for the feedback. Let us bring this up with our teams.

**Comment by guilhermeojs** [comment]
Any improvements on this @shue249 ? If the user doesn't allow Facebook to track its activity the popup message to track it keeps popping up also with the messenger plugin.

What annoys the most (got feedback from multiple customers) is the messenger popup

**Comment by shue249** [comment]
@guilhermeojs Apologies for the delay.

1. Will you be able to share a screenshot of how the messenger popup looks like on your mobile website.

2. Can you explain more on the point of doesnt allow Facebook to track its activity.

**Comment by guilhermeojs** [comment]
> @guilhermeojs Apologies for the delay.
> 
> 1. Will you be able to share a screenshot of how the messenger popup looks like on your mobile website.
> 2. Can you explain more on the point of doesnt allow Facebook to track its activity.

No worries.

I've uploaded the screenshot and the video to make it easier. Let me know if you need anything else.

https://drive.google.com/drive/folders/1MCTkhqGxpWPkOG8UyQDXE_q_W0XJLD4R?usp=sharing

**Comment by shue249** [comment]
@guilhermeojs Thanks for the screenshot and the videos.

1. For the mobile. Your earlier feedback is that the messenger chat plugin takes up most of the screen on the mobile. However, from your video, I see that it is only occupying a small area at the bottom of your screen. Can I understand how will your ideal view be?

2. For the desktop, it seems that the this is happening on safari? Is there any settings that you made to show the privacy prompt up? We tested on our Safari and is unable to make the privacy prompt appear. Also on our side, Chrome does not have this issue.

**Comment by guilhermeojs** [comment]
> @guilhermeojs Thanks for the screenshot and the videos.
> 
> 1. For the mobile. Your earlier feedback is that the messenger chat plugin takes up most of the screen on the mobile. However, from your video, I see that it is only occupying a small area at the bottom of your screen. Can I understand how will your ideal view be?
> 2. For the desktop, it seems that the this is happening on safari? Is there any settings that you made to show the privacy prompt up? We tested on our Safari and is unable to make the privacy prompt appear. Also on our side, Chrome does not have this issue.

1. I've definitely exaggerated with the "takes up most of the screen" - I do have a big mobile phone, but I always wonder how is the UX for an user who doesn't own a big one. The worst thing is that even if you click to close the messenger on "X" it keeps popping it up and opening it again.

2. I didn't record the desktop video, it was a friend of mine using it Safari so I can't tell you much about his settings though. The best thing to focus on might be the mobile popup actually.

I've used other platforms for chatting with customers (like Tawk, JivoChat, etc) for OpenCart and they usually have an option for you to set time triggers for the popup and also if you want it to pop or not.

**Comment by shue249** [comment]
@guilhermeojs We did some tests on your website from our development devices.

1. For the mobile, we tested on Android Chrome, iOS Safari and iOS Chrome. Here are our observations:
Android Chrome - problem not happening
iOS Safari, if we do not accept the privacy tracking - problem happening
iOS Safari, if we accept the privacy tracking - problem not happening
iOS Chrome - problem not happening
Based on our observations, this problem only occur for iOS Safari if we did not accept the privacy tracking.

2. For the desktop, we tested on Chrome, Safari and Firefox from MacOS device.
Here are our observations:
Chrome - problem not happening
Safari - problem not happening and unable to trigger the privacy tracking
Firefox - problem not happening
Based on our observations, this problem seems to only occur for Safari.

In overall, our observations suggest that the problem happen only for Safari and perhaps when consumer choose not to accept the privacy tracking. I will share this feedback with our product team.

**Comment by shue249** [comment]
@guilhermeojs Our Messenger team have resolved the issue on popup happening on Safari due to the privacy tracking acceptance. You can take a look to see how the effect looks like.

Will be closing out this ticket, feel free to reach to us if you have further questions.
