### ISSUE TITLE
There is an error with Facebook Business Extension setup

### ISSUE THREAD

**Issue by kokobongoton** [facebookincubator/Facebook-For-OpenCart#229]
Hello,
My web site is www.stokatastoki.bg,the mistake is:

### There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup. Please contact Facebook via our Github if this error keeps showing.

Please help me, I do not understand why the module does not work?
Before it worked, I saw that there was a new version, I decided to update and then I got this problem, I tried the recommendations, but without effect, I also attached the log file.

[StokataStoki - Онлай магазин_2019-08-17_10-43-21_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3511770/StokataStoki.-._2019-08-17_10-43-21_facebook_ads_extension.log)

Thanks in advance.

**Comment by kokobongoton** [comment]
Did I get another type of error?
 There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 27140 products). Please refer to our FAQ section on "Syncing of OpenCart products to Facebook catalog" for more details.

Again I attach the log file.

[StokataStoki - Онлай магазин_2019-08-17_11-01-43_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3511775/StokataStoki.-._2019-08-17_11-01-43_facebook_ads_extension.log)

**Comment by shue249** [comment]
@kokobongoton From the latest log file, we can see that the generating of the initial feed file did not complete successfully, as there are too many products on your Opencart site. We have a catalog section in FAQs that describes some of the ways to solve the problem - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog. Can you take a look and see if it helps you.

**Comment by kokobongoton** [comment]
Hello,  Thanks for your reply,  I deactivated about 3400 products but again got an error.  How many products can be poured into the Facebook catalog, is there any option in the module itself not to pour products with stock 0?  Thank you in advance,  Have a nice day!  
 







 >-------- Оригинално писмо --------

 >От: shue249 notifications@github.com

 >Относно: Re: [facebookincubator/Facebook-For-OpenCart] There is an error with
 Facebook Business Extension setup (#229)

 >До: facebookincubator/Facebook-For-OpenCart  

 >Изпратено на: 19.08.2019 05:14



 
 
  
 @kokobongoton  From the latest log file, we can see that the generating of the initial feed file did not complete successfully, as there are too many products on your Opencart site. We have a catalog section in FAQs that describes some of the ways to solve the problem -  https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog . Can you take a look and see if it helps you.

**Comment by shue249** [comment]
@kokobongoton We have released a latest version 2.2.0 which improves the catalog sync. 

1. You can delete away the existing plugin, install the latest version, delete away the existing settings and re-do the setup again.

2. If the catalog still fails due to the large size, you can make changes to the plugin code to exclude away 0 stock if you have development resources. The code pointer will be here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/model/extension/facebookproduct.php#L15. What you need to do is to include in the 0 quantity as a WHERE clause to the SQL query.

Do take note that any local changes you make to the plugin on your local server will be over-written whenever you install a later version of the plugin.

We will be closing out this ticket. Feel free to reach to us if you have any further questions.
