### ISSUE TITLE
Regex for editing descriptions

### ISSUE THREAD

**Issue by siteadvice** [facebookincubator/Facebook-For-OpenCart#240]
Hi there
I use shortcodes in my Opencart descriptions which are enclosed within square brackets.
So, I'd like to add a regular expression to the Facebook extension to omit content within square brackets.
Can you please tell me where the code needs to go?
Is it system\library\facebookproductformatter.php in the function getDescription()?
Thanks.

**Comment by shue249** [comment]
@siteadvice This is the location where you need to make the changes - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L112

Will be closing out this ticket, feel free to reach to us if you have further questions.

**Comment by siteadvice** [comment]
Thanks. That's what I thought. 
Is there a URL where I can preview the feed?

**Comment by shue249** [comment]
@siteadvice For the individual product updates, you cannot preview the feed as we are using direct API to make the updates. There is a feature to Re-sync all the products to Facebook. For this feature, we are using the feed file. If you like to view the feed file, you can look at this method and make your changes - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproductfeed.php#L55

Specifically:
1. This is the feed filename and location - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproductfeed.php#L55. You can output the file name to quickly locate the file.

2. This is where we are removing away the feed file after the upload to facebook - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproductfeed.php#L142. You can comment away this line so that the feed file remains on the system

3. This is where we are doing the actual upload - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookproductfeed.php#L129. You can comment away this line to prevent the file from being uploaded to Facebook.
