### ISSUE TITLE
Your plugin just crashed my entire site!?!?

### ISSUE THREAD

**Issue by adamford4** [facebookincubator/Facebook-For-OpenCart#25]
Everything - can't login to backend - entire site is down.

YOU need to send help URGENTLY, what on earth is with this?

**Comment by shue249** [comment]
Thank you for the feedback. 
Can you try to access your admin panel server URL with this path - index.php?route=extension/modification. You should be able to access the plugin. Select the plugin to remove it and click on the blue refresh icon. Your backend should be fine now. 

At the same time, we will like to understand more on what happened so that we can further improve on our plugin. Will you be able to access your server logs and send us the recent activity so that we can identify the error which caused the problem.

**Comment by shue249** [comment]
Our plugin requires to save in some new files to some opencart sub-folders on your webserver. Can you take a look to see if the admin, catalog and system sub-folders are writeable on your opencart folder.

**Comment by shue249** [comment]
Thank you again for your feedback. Based on our understanding, the plugin may not have been installed correctly leading to the problem of of the website being unavailable. To now, the website has been brought back up. 

We will be happy to take on any insights/suggestions from you or your team on how we can improve the plugin. We will proceed to close off the ticket, but feel free to re-open or create a new ticket for any new insights.
