### ISSUE TITLE
product_language_text Dropdown menu not shown in second language

### ISSUE THREAD

**Issue by nhoangnam93** [facebookincubator/Facebook-For-OpenCart#279]
product_language_text Dropdown menu not shown in second language in admin

**Comment by shue249** [comment]
@nhoangnam93 Thank you for the feedback. We have updated the plugin again due to some build errors earlier. Can you download and re-install the plugin from OpenCart marketplace or github - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13

The product_language_text feature is still in development and is not part of this release.

Will be closing out this ticket. Feel free to reach to us if you have further questions.
