### ISSUE TITLE
AddToCart not show data

### ISSUE THREAD

**Issue by raix022** [facebookincubator/Facebook-For-OpenCart#280]
Hello, 

PageView and ViewContent is working fine, but I dont see activity in AddToCart and Purchases.
OC version is  3.0.2.1 and Plugin Version: 2.1.13. We use there Sello theme. In facebook I see last time it worked 19 days ago.

**Comment by raix022** [comment]
Also I see error:

 We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have Refresh the modifications, View steps
2. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
3. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

All those setps are fine and checked.

**Comment by shue249** [comment]
@raix022 Can you share your web store URL?

**Comment by raix022** [comment]
airvitamin.ee

**Comment by raix022** [comment]
> @raix022 Can you share your web store URL?

airvitamin dot ee

**Comment by raix022** [comment]
U find it? I try everything, but its not working..

**Comment by shue249** [comment]
@raix022 From our check, things are working. You can try to make a dummy purchase on your website and inspect the events using our PixelHelper tool.

On AddToCart: (we are not able to test out purchases as it will involve an actual purchase, but you can do this mock test yourself)
![image](https://user-images.githubusercontent.com/11957585/67644655-40bed100-f95e-11e9-89dc-40ee2a66a2f7.png)

![image](https://user-images.githubusercontent.com/11957585/67644664-59c78200-f95e-11e9-8bb7-952e14368766.png)

From your FB analytics, we can see that the AddToCart and Purchase are captured
![image](https://user-images.githubusercontent.com/11957585/67644690-b034c080-f95e-11e9-930b-a85138f6120e.png)

Similarly, on Pixel dashboard, we are also able to see AddToCart and Purchase
![image](https://user-images.githubusercontent.com/11957585/67644703-d9ede780-f95e-11e9-8c13-2a2a1265fe7e.png)

Did you insert in any custom pixel codes? Can you remove those custom pixel codes?

**Comment by raix022** [comment]
Hello,
When I test with PixelHelper, I see it not working. 
![Screenshot 2019-10-28 at 10 51 22](https://user-images.githubusercontent.com/42356724/67664884-30642180-f971-11e9-97c0-888094e9b3b4.png)
I dont have any custom pixel codes. In FB analyst you see, its working some days ago. Every day this shop get 2-6 orders.

**Comment by raix022** [comment]
And also Purchase not working. 

![Screenshot 2019-10-29 at 17 03 21](https://user-images.githubusercontent.com/42356724/67780007-2411be80-fa6e-11e9-99bc-bd04e46160c3.png)

**Comment by shue249** [comment]
@raix022 There are 5 things to discuss here.

1. We believe that your website is running an older version of the plugin, possibly due to caching. Can you check if you have disabled the theme and SASS cache and to ensure that you have refreshed the modifications
a. https://drive.google.com/open?id=1bY-bworYxX36b88HDvFW0_32C3Wtq_Tm
b. https://drive.google.com/open?id=1qy-ipwK1HCk8oSnUmGuy6MCJxQdUyGfw

![image](https://user-images.githubusercontent.com/11957585/67820540-a47b0280-faf4-11e9-9c17-6c36e9747ea7.png)

2. The error that you are seeing on the Facebook Business Extension module is also because, the latest plugin could not locate the latest codes on your website. Once the cache is disabled, the latest codes is running on the website, the error will be gone.

3. We have found existing pixel codes on your website. Can you remove these from your website.

![image](https://user-images.githubusercontent.com/11957585/67821146-ee64e800-faf6-11e9-880b-044d25f69a75.png)

4. On the aspect for AddToCart, we have found existing pixel codes for AddToCart, which results in the warning that you are seeing on your screenshot. We recommend to remove away these codes. For your own testing, if you proceed to click on the Add To Cart button, you will be able to see that our AddToCart event is now fired. 

![image](https://user-images.githubusercontent.com/11957585/67820773-8f52a380-faf5-11e9-9609-68e5db22606f.png)

![image](https://user-images.githubusercontent.com/11957585/67820967-4ea75a00-faf6-11e9-959f-643642bcbef0.png)

5. We were not able to debug the purchase, as it involves us making an actual purchase. You can follow the guidelines above to apply for Purchase.

**Comment by raix022** [comment]
Hello,
I delete all old code from header and reinstall the plugin. Now I see new code there, but Facebook Pixel Helper dont show any data now. Also in admin Facebook Business Extension error is gone, I dont see any error there. 

![Screenshot 2019-10-30 at 10 54 32](https://user-images.githubusercontent.com/42356724/67843325-6ab1f800-fb04-11e9-983a-eefb116ff713.png)
![Screenshot 2019-10-30 at 10 54 37](https://user-images.githubusercontent.com/42356724/67843334-6ede1580-fb04-11e9-83df-9bb9ff3d8d41.png)

**Comment by raix022** [comment]
U can close it.
