### ISSUE TITLE
Product not cached in pixel

### ISSUE THREAD

**Issue by rightmarc** [facebookincubator/Facebook-For-OpenCart#292]
Total 2 error receive in 
1. A required field is missing: id
Products without "id" information can't be uploaded. Please check that this field is included for each product in a separate, labeled column.

2.There is an error with Facebook Business Extension setup. Click on Facebook Business Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.
The sync failure of your products to Facebook may be because of the large number of products on your system (We detected 227503 products). Please refer to our FAQ section on "Syncing of OpenCart products to Facebook catalog" for more details.

**Comment by shue249** [comment]
@rightmarc 

Can you share with us a copy of your log file from the plugin here? We suspect that the feed file was not successfully generate due to the large number of products on your website.

Are you able to review this FAQ section to see if the points help you - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

**Comment by shue249** [comment]
@rightmarc We will be closing out this ticket, but pls feel free to reach to us if you have any further questions.

**Comment by sabryanwar** [comment]
Products without "id" information can't be uploaded. Please check that this field is included for each product in a separate, labeled column.
what can i do to solve this problem

**Comment by yao-tx** [comment]
Hi @sabryanwar, please open a support ticket with us at https://marketinsg.zendesk.com. Thank you.
