### ISSUE TITLE
Facebook Extension

### ISSUE THREAD

**Issue by Netsaypro** [facebookincubator/Facebook-For-OpenCart#300]
We are facing a technical problem of installing facebook extension. For more information, please check the attached picture. We have already follow the guideline to delete and reinstall but still cant finish. How to fix it?

![Capture](https://user-images.githubusercontent.com/58498198/70110581-6be9be00-168a-11ea-9245-50f40b511818.JPG)

Moreover, we want to link our opencart onlinehop to facebook store. We need to use plugin or other methods? Can you provide us some guideline.

**Comment by shue249** [comment]
@Netsaypro Can you download the plugin log file and share it here for us to debug further on the problem.

For direct linking of your products to Facebook page shop, you can also manually create your own catalog and then linking it to page shop. You can read up more details here https://www.facebook.com/business/help/890714097648074?id=725943027795860

This plugin helps to automate all the steps and auto sync the catalog so that you do not have to do them yourself.

**Comment by shue249** [comment]
@Netsaypro Can you also share a screenshot of your Facebook Business Extension module.

![image](https://user-images.githubusercontent.com/11957585/70111090-1c0bf680-168c-11ea-9854-2d347175c9ea.png)

**Comment by Netsaypro** [comment]
Dear Shue249,

 

I have deleted the Facebook Business Extension as the warning massage always show on the backend.



 

I have already followed the above guideline but still have bug

 

Best Regards,

Pang

**Comment by shue249** [comment]
@Netsaypro Will you still be keen to use our plugin? if so, can we ask for you to re-install the latest version of the plugin, delete away the settings and re-setup Facebook Business Extension. After which, please share with us the error status (if any) of the plugin so that we can help you to troubleshoot.

Latest version of plugin - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.13
Re-install and delete away existing settings - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#delete-the-existing-settings-for-facebook-for-opencart

**Comment by Netsaypro** [comment]
Dear Shue249,

 

I have re-installed the plugin. Our opencart products are being imported to Facebook. I waited for a whole day but still not yet finish. 

 

Please see the attached photos to know more our situation.

 

When will finish the whole importing procedure? 

 

Actually, we want to set up a facebook store same as the attached photos named “Facebook Store”. After the importing procedure, our facebook store will become like this one?

 

Best Regards,

Pang

**Comment by Netsaypro** [comment]
Dear Shue249,

 

Any updates?

 

Dear Shue249,

 

I have re-installed the plugin. Our opencart products are being imported to Facebook. I waited for a whole day but still not yet finish. 

 

Please see the attached photos to know more our situation.

 

When will finish the whole importing procedure? 

 

Actually, we want to set up a facebook store same as the attached photos named “Facebook Store”. After the importing procedure, our facebook store will become like this one?

 

Best Regards,

Pang

 

Best Regards,

Pang

 

From: enquiry@netsaypro.com <enquiry@netsaypro.com> 
Sent: Thursday, December 5, 2019 7:42 PM
To: 'facebookincubator/Facebook-For-OpenCart' <reply@reply.github.com>; 'facebookincubator/Facebook-For-OpenCart' <Facebook-For-OpenCart@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [facebookincubator/Facebook-For-OpenCart] Facebook Extension (#300)

 

Dear Shue249,

 

I have re-installed the plugin. Our opencart products are being imported to Facebook. I waited for a whole day but still not yet finish. 

 

Please see the attached photos to know more our situation.

 

When will finish the whole importing procedure? 

 

Actually, we want to set up a facebook store same as the attached photos named “Facebook Store”. After the importing procedure, our facebook store will become like this one?

 

Best Regards,

Pang

**Comment by shue249** [comment]
@Netsaypro Apologies for the delay.

1. How many products do you have on your opencart website?

2. Can you delete away the existing settings and re-do the setup again. You can follow this video guide here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#delete-the-existing-settings-for-facebook-for-opencart

3. Can you download and share the log file from the Facebook Business Extension module page so that we can debug further.

**Comment by Netsaypro** [comment]
Dear Shue249,
I have deleted and reinstall the extension.
Opencart products is being Imported to Facebook store. We have 4039 products in opencart.
    	
    	

    	取得 iOS 版 Outlook
    
  




On Fri, Dec 6, 2019 at 10:43 PM +0800, "shue249" <notifications@github.com> wrote:












@Netsaypro Apologies for the delay.




How many products do you have on your opencart website?




Can you delete away the existing settings and re-do the setup again. You can follow this video guide here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#delete-the-existing-settings-for-facebook-for-opencart




Can you download and share the log file from the Facebook Business Extension module page so that we can debug further.

**Comment by shue249** [comment]
@Netsaypro 

Can we verify with you if your website URL is https://netsaypro.com/. The reason being that we still see the plugin version listed as 2.1.3 instead of our latest 2.2.0 version when viewing the source code of the website. You can download the version 2.2.0 here - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.2.0

![image](https://user-images.githubusercontent.com/11957585/70403253-4afde000-1a71-11ea-9932-0b67112fb6f9.png)

**Comment by Netsaypro** [comment]
Dear Shue249,

 

I have re-install the latest version. The opencart products start to be imported to Facebook again. Please see the attached screenshot for your reference.

 

When will the importing process finish?

 

Best Regards,

Pang Wong

**Comment by shue249** [comment]
@Netsaypro Thanks, we have found the latest version on your OpenCart website. Can we ask for you to do 2 more things. Please reply back directly to the github ticket on your browser instead of replying from email as any attachments will not be added to the ticket.

1. Can you delete away the existing settings (NOT the plugin) and re-do the setup again. https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

2. After the re-setup is done, can you share with us the log file of the plugin here. We suspect there is some error during the setup and catalog sync and the feed file may provide us some clues on where could the error(s) be.

![image](https://user-images.githubusercontent.com/11957585/70416622-7943e580-1a9a-11ea-9c47-34e4729ec19b.png)

**Comment by Netsaypro** [comment]
Dear Shue249,

 

I don’t know how to reply through the github ticket. Can you give me the link?

 

The re-setup is done and please find the attached log file.

 

Best Regards,

Pang Wong

**Comment by shue249** [comment]
@Netsaypro This is the link for the github ticket - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/300

I wasnt able to see the log file. Can you attach the log file directly to this ticket from your browser.

**Comment by Netsaypro** [comment]
Here is the log file
[NetSayPro 醫美產品購物網_2019-12-09_08-00-37_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3938525/NetSayPro._2019-12-09_08-00-37_facebook_ads_extension.log)

**Comment by shue249** [comment]
@Netsaypro 

1. We found that 4.2K products are uploaded to the Facebook catalog. https://www.facebook.com/products/catalogs/790529928054428/products

2. The Facebook shop also has the products uploaded

3. However, the product images are not displayed successfully.
![image](https://user-images.githubusercontent.com/11957585/70421882-b06bc400-1aa5-11ea-9fc8-b05852339a2a.png)
![image](https://user-images.githubusercontent.com/11957585/70421916-bc578600-1aa5-11ea-8d1a-e83b19579d13.png)

We will continue to look into the catalog image issue. At the same time, can you look at point 5 of this FAQ to see if the 2 points work for you - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/FAQ.md#syncing-of-opencart-products-to-facebook-catalog

**Comment by shue249** [comment]
@Netsaypro We looked at your feed file at this URL - http://netsaypro.com/index.php?route=extension%2Ffacebookfeed%2FgenFeed

The CSV feed file shows that the image field shows up the image_link for all products as just http://netsaypro.com/image/

We like to check with you if you are using 3rd party product management module or 3rd party product image modules?

**Comment by Netsaypro** [comment]
Our IT consultant said he upload product photos via FTP link not backend. 

How to solve this problem

**Comment by shue249** [comment]
@Netsaypro How do you link the product to the images on your Opencart? There should be some data stored on the MySQL database which links the product images.

**Comment by shue249** [comment]
@Netsaypro Like to follow up with you on this. Any suggestions/updates from your IT team on the image information stored on the database?

**Comment by shue249** [comment]
@Netsaypro We will be closing out this ticket for now, feel free to reach to us if you have further questions.
