### ISSUE TITLE
Product Tags input to custom_label

### ISSUE THREAD

**Issue by bonyod** [facebookincubator/Facebook-For-OpenCart#305]
Hi, is there any way to put product tag to custom label? If I need to customize myself, what file should I check/update?
Thank you

**Comment by shue249** [comment]
@bonyod Currently we do not provide this feature in the plugin, but we can suggest the code pointers if you have development resources. Pls do take note that the changes made on your local server will be overwritten whenever you re-update the plugin to a later version, so you need to make the changes again if you do update the plugin.

1. We strongly suggest for you to upgrade the plugin to latest 2.2.0 version as we have deprecated the API approach and is fully 100% using the feed approach. Our suggestions will also only be focused on feed approach

2. This is the method function which contains the feed file generation - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L93

3. You need to add in the new fields to the feed file header row here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L190

4. You need to add in the new fields to the SQL query so that the model is able to return back the data (note that this method is largely duplicated from OpenCart) - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/model/extension/facebookproduct.php#L15

5. You need to add in the new fields to be transferred from model product array to Facebook formatted product array here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L87

6. You need to add in the new fields to be returned as CSV format here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L197

**Comment by bonyod** [comment]
perfect! thank you @shue249 !

**Comment by shue249** [comment]
@bonyod You may have already know this, but want to over-communicate here.

1. You can check the physical CSV feed file from this location - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/controller/extension/facebookproductfeed.php#L71

2. You can check the Facebook product catalog documentation and the list of available fields here - https://developers.facebook.com/docs/marketing-api/catalog/reference
