### ISSUE TITLE
Chat doesn`t appear

### ISSUE THREAD

**Issue by Aukvito** [facebookincubator/Facebook-For-OpenCart#311]
Hi there :)

I really love your module. Specially for it`s products export to fb page.

But I have custom theme installed on the opencart and I think that`s why FB chat doesn`t appear on my web-site - vsvua(dоt)com.
So, what do I have:
1. OC store 2.3.0.2.3 (Opencart modyfied for russian-speaking countries).
2. BurnЕnginе with custome template (trеndо).
3. There is no theme`s cache manager.
4. FB Business Extension 2.2.1.
5. Standard error message
![image](https://user-images.githubusercontent.com/52528405/70795261-14450400-1da8-11ea-8826-8c8c7cab776e.png)

What`s done:
1. Permissions given,
2. Modifications refreshed.
3. Opencart and hosting cache cleared.

I attach .tpl files and logs:
1. [VSV_2019-12-13_13-00-59_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3960423/VSV_2019-12-13_13-00-59_facebook_ads_extension.log)
2. [storage_modification_catalog_view_theme_template_common.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3960426/storage_modification_catalog_view_theme_template_common.zip)

Thank you in advance for your great work

**Comment by shue249** [comment]
@Aukvito Thanks for your support!

1. The Facebook customer chat plugin is not showing because we require your webstore URL to be HTTPS and have a domain name. We found that your website is not HTTPS and hence it is not loading. You can read more on the requirements here - https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/#steps

2. A quick test on your website shows that your pixel is correctly firing from your website

3. We found that you have installed an optimizer on your website which causes our pixel diagnostics to report a false negative. You can safely ignore the pixel incorrectly setup warning message on the Facebook business extension module.

We will relook into the pixel diagnostics mechanism to see if we can further improve on this.

**Comment by Aukvito** [comment]
@shue249 Thanx for your answer!

I configured https properly on my website, cleaned cache and reconfigured fb chat but it still doesn`t appear. Any more suggestions?

Here are actual logs 
[VSV_2019-12-23_20-46-29_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3995914/VSV_2019-12-23_20-46-29_facebook_ads_extension.log)

**Comment by shue249** [comment]
@Aukvito Apologies for the late reply.

One more suggestion, can you try to disable your web optimizer to see if it helps to solve the problem where the fb chat is not appearing? If you view source of your website, we want to verify that the codes for the fb chat is properly inserted into the website and then to check if it helps to force the fb chat to appear.

**Comment by shue249** [comment]
@Aukvito We will be closing out this ticket. Feel free to reach to us if you have further questions.
