### ISSUE TITLE
problem with feed url

### ISSUE THREAD

**Issue by reginamor** [facebookincubator/Facebook-For-OpenCart#32]
i've installed the extension and i have a problem with the url of the feed, because when i've installed the https certificated, i have to erase the url on the config files (i don't have url)
Where can i chage the url of the feed? i try to find the file that sends this configuration, but i can't found it. Thanks

**Comment by shue249** [comment]
@reginamor Thank you for your feedback.

For the initial product sync, we are not using a feed URL, but uploading the feed file to Facebook catalog directly. Hence you are unable to find any URL config on the Facebook feed.

For the detailed explanation. We are adopting a 2 mechanism approach to ensure a good experience for you when you setup the Facebook Ads Extension. When you completed the setup, we will automatically create a Facebook product catalog and sync all your OpenCart products through the use of a one time feed file. This is using the direct upload of the feed file rather than using a feed url. This ensures a smooth operation even if you have a large number of products on your store. Subsequently, we will send real time product updates to Facebook whenever you make changes or new additions to your OpenCart products using API approach.

We will be closing out this ticket, but pls feel free to open up again if you have any further feedback.

**Comment by reginamor** [comment]
Hi!
Yes you pick a url from somewhere, because on facebook you put the link of the product.
FAcebook do not acept my products because the URL is wrong.

If the url is "www.domain.com/category/product" in facebook apears: "/category/product" the domain desapear and you reject my product on my facebook catalog.
![captura de pantalla 2018-02-07 a las 13 32 01](https://user-images.githubusercontent.com/27919921/44922729-70684e00-ad46-11e8-9760-6fb49c042af4.png)

On my opencart panel i erase the domain of my website because the ssl certificate do not works.
![captura de pantalla 2018-08-31 a las 17 51 38](https://user-images.githubusercontent.com/27919921/44922762-8c6bef80-ad46-11e8-84eb-19bf593c215b.png)

So like i said before, facebook take the url of my website from somewhere, because i guess that you are not fortune tellers to know what my url is

**Comment by shue249** [comment]
@reginamor Thanks for your feedback!

You are right that we are getting the website URL from your OpenCart server. We are using the HTTP_CATALOG variable found in the config.php on your OpenCart server. We are using this variable on this line of code - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L154

![image](https://user-images.githubusercontent.com/11957585/45063356-686c1f00-b062-11e8-9e98-c11bf1b3f0b2.png)
