### ISSUE TITLE
Install problem 

### ISSUE THREAD

**Issue by nonanik123** [facebookincubator/Facebook-For-OpenCart#333]
The extension does not go past the opening page. It keeps loading for ever and I cannot access the setting pages.

**Comment by shue249** [comment]
@nonanik123 Is this a fresh installation of our plugin or did you upgrade the plugin from an older version to a newer version?

If you did the upgrade, there is a chance that the old JS files are still cached on your browser. Can you do a Empty cache and hard reload on your browser and see if you can load the page successfully.

If the above method does not work or if this is a fresh installation, can you share a screenshot of how the problem looks like so that we can better understand the problem.

**Comment by teddybearsurf** [comment]
I'm having the same problem. It gets stuck on the finish setup page. Just keeps loading. Can't get past it. It is a fresh install.

**Comment by shue249** [comment]
@teddybearsurf Can you share a screenshot of how it looks like.

**Comment by teddybearsurf** [comment]
![Capture+_2020-03-26-09-30-03](https://user-images.githubusercontent.com/47298839/77652403-89e27380-6f44-11ea-9cd9-f5d370d1ffed.png)

**Comment by teddybearsurf** [comment]
That's the page it's stuck on.

**Comment by shue249** [comment]
@teddybearsurf Thank you for the feedback. We see that you are completing the setup flow on a mobile device. At the moment, setup via mobile is not supported. Can you switch to use a desktop browser to complete the setup instead.

**Comment by teddybearsurf** [comment]
Yes I switched to my laptop and it worked. Thank you for your help. ☺

**Comment by shue249** [comment]
@teddybearsurf Glad that it works for you.

**Comment by shue249** [comment]
@nonanik123 Wondering if you have any updates to your problem? Are you able to share more details or any screenshots?

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.
