### ISSUE TITLE
Problem with sync products 

### ISSUE THREAD

**Issue by Carnergr** [facebookincubator/Facebook-For-OpenCart#343]
Hello, we use Facebook adds old version and we had some error when try to resync products, now we put the newest version 3,0 and when try to sync products we have message that product catalog is empty. Before update we had in open cart under the “GET STARTED” the store ID , but now we have nothing just the Get started, when we make sync products we have error! Please let us know how to fix!

Thank you

**Comment by dtying** [comment]
Hi @Carnergr, can you provide me the url of your web store? Thanks.

**Comment by Carnergr** [comment]
Hello,

The url of our website is www.carner.gr and our facebook page is
facebook.com/carner.gr


Ioannis Simeonidis
Managing Director
Proektasi Maiandrou,Ring road Evosmos
Thessaloniki , 57013 ,Greece ,P.O. Box 118
Tel.:2310 688 872, 2310 688 482
Fax:2310 688 036
www.carner.gr
www.car.gr/carner
facebook : CARNER.GR <http://carner.gr/>
twitter @CARNERGR



*P* *Please consider the environment before printing this e-mail*

*GO **GREEN* *–* *Climate Protection with **Carner SA*


Στις Τετ, 8 Απρ 2020 στις 10:56 π.μ., ο/η dtying <notifications@github.com>
έγραψε:

**Comment by dtying** [comment]
Thanks @Carnergr for your info. Here're my findings:
1. I see that after you upgraded FBE, you have uninstalled and reinstalled for several times.
2. In you latest installation, the **feed schedule** had been removed from your Facebook Catalog. This is the reason why your Facebook Catalog is out of sync from OpenCart. Please note that the feed schedule should never be deleted.

In order to fix this issue, can you try:
1. Uninstall and reinstall your FBE plugin.
2. Once installed successfully, click on 'Management View' button, navigate to 'Catalog' tab, and follow the link to open Facebook Catalog Manager.
3. In your Facebook Catalog Manager, navigate to 'Product Data Sources', verify that the feed schedule is correctly setup. By default the schedule is on a daily basis.
![Screen Shot 2020-04-08 at 5 06 21 PM](https://user-images.githubusercontent.com/21333308/78766414-cfc71f00-79bb-11ea-960e-b9c5c89cfabb.png)

**Comment by Carnergr** [comment]
Hello,

Thanks for reply!
Yes i delete several times FBE..
I am little confused now!
I delete all but still remain an old upload (product catalog) in facebook
and still working..

Also regarding my pixel seems i have 2 or more pixels in my account maybe
by my wrong or not?

Now i have to deltete at all the extension from open cart and reinstall it
, should i make also something on facebook?

XML feed is automatically generated from the extension or i must do
something?

Thanks for support!
John

>

**Comment by dtying** [comment]
@Carnergr  I see ...
As you're not sure which catalog is connected to your page shop, you can refer below to verify it. If you don't see the section like this, it means your catalog currently is not connected to your Page Shop.
![Screen Shot 2020-04-08 at 6 13 43 PM](https://user-images.githubusercontent.com/21333308/78773236-811e8280-79c5-11ea-80c5-4d239176053c.png)



I also verified your pixel, it looks good, only one pixel_id is found there. Pixel Helper displayed 2 because it detected 2 pixel events.

Feed generation is done by FBE automatically. I don't think you have to remove other extensions. Please just uninstall and reinstall FBE itself and try first.

**Comment by Carnergr** [comment]
Hello,

Finally i did it!!!
Catalog uploaded but i have a problem with more than 50% of products that i
didnt have problem before(check pictures)

[image: fbe 2.png]
[image: fbe.png]

Also in open cart page i dont see store ID as before just see the Get
started!
[image: fbe 3.png]
Ioannis Simeonidis
Managing Director
Proektasi Maiandrou,Ring road Evosmos
Thessaloniki , 57013 ,Greece ,P.O. Box 118
Tel.:2310 688 872, 2310 688 482
Fax:2310 688 036
www.carner.gr
www.car.gr/carner
facebook : CARNER.GR <http://carner.gr/>
twitter @CARNERGR



*P* *Please consider the environment before printing this e-mail*

*GO **GREEN* *–* *Climate Protection with **Carner SA*


Στις Τετ, 8 Απρ 2020 στις 1:22 μ.μ., ο/η dtying <notifications@github.com>
έγραψε:

**Comment by dtying** [comment]
@Carnergr Hi, I checked that some of your products were diagnosed with issues with Dynamic Ads eligibility, you may refer to https://www.facebook.com/policies/ads for details. 

Did you see any error prompted after FBE installation? If everything went well, your FBE page will be reloaded automatically to show 'Management' and 'Uninstall' button.

**Comment by dtying** [comment]
Hi @Carnergr, I'm closing out the ticket for now. Feel free to contact us should you have any further questions.

**Comment by Carnergr** [comment]
Hello,

Thank you for your help!

Ioannis Simeonidis
Managing Director
Proektasi Maiandrou,Ring road Evosmos
Thessaloniki , 57013 ,Greece ,P.O. Box 118
Tel.:2310 688 872, 2310 688 482
Fax:2310 688 036
www.carner.gr
www.car.gr/carner
facebook : CARNER.GR <http://carner.gr/>
twitter @CARNERGR



*P* *Please consider the environment before printing this e-mail*

*GO **GREEN* *–* *Climate Protection with **Carner SA*


Στις Δευ, 13 Απρ 2020 στις 1:00 μ.μ., ο/η dtying <notifications@github.com>
έγραψε:
