### ISSUE TITLE
Issu whit Jouranl Theme 2

### ISSUE THREAD

**Issue by exitsport** [facebookincubator/Facebook-For-OpenCart#352]
Hi,

We upgrade extension  for 3.0 but after that not work Header Notice in Top bar, Messenger not show  anymore and not impossible to change account in Facebook Extension

**Comment by dtying** [comment]
Hi @exitsport , thanks for your feedback.

- Could you share more about 'Header Notice in Top bar'? What feature do you expect to have?
- Messenger is currently unavailable in this version due to upgrade. Will be ready in next release.
- Could you also share more about 'Change account in FBE'? Our idea is FBE is for one-time setup only.

**Comment by exitsport** [comment]
If we choosed page, the page not found and not impossible to change that in the extension

**Comment by dtying** [comment]
Hi @exitsport , we have recently updated the FBE UI to show the pages which you don't have access to in grey color, and when you hover on it, it also tells the reason why you can't select that page. I hope this can help you to solve this issue.
