### ISSUE TITLE
Fatal error: Uncaught Error: Class 'FacebookCommonUtils' not found in

### ISSUE THREAD

**Issue by ankitjn227** [facebookincubator/Facebook-For-OpenCart#374]
Got the same error today..

Did anyone find the solution, plz help/

_Originally posted by @ankitjn227 in https://github.com/facebookincubator/Facebook-For-OpenCart/issues/277#issuecomment-618025864_

**Comment by shue249** [comment]
@ankitjn227 

1. Can you check if you have provided read+write access to the admin, catalog and system folders. The problem that you are facing is because some of the plugin files are not successfully copied over to your OpenCart webserver. After you set the read+write permissions, pls ensure that you remove away the plugin and re-install the plugin again.
![image](https://user-images.githubusercontent.com/11957585/80059825-8e0faa00-855f-11ea-84d1-5869fdba66a7.png)

2. What is the plugin version. Are you using the latest version 3.0.0?

**Comment by shue249** [comment]
@ankitjn227 Can you try to access this URL on your opencart admin panel - admin/index.php?route=marketplace/modification. Are you able to access the modifications? If you can access, pls delete away the plugin and click on Refresh Modifications.

The problem you are facing is because the files are not copied over correctly because of invalid read+write permissions on the admin, catalog and system folders.

**Comment by ankitjn227** [comment]
@shue249 Issue Resolved

Thanks ..

**Comment by skashif144** [comment]
@shue249 thanks !
