### ISSUE TITLE
How to configure the  Event Initiate Checkout fb pixel ( partner integration opencart)

### ISSUE THREAD

**Issue by hassni1** [facebookincubator/Facebook-For-OpenCart#382]
fb pixel successfully integrate with opencart partner , but i checked some events are not configure. so i configure them manually like initiate checkout and purchase 

it gives an error on value , how to fix the issue 

Please check the attachment 
https://prnt.sc/s9k0ae

Best Regards

**Comment by shue249** [comment]
@hassni1 Can you share with us a screenshot of the pixelhelper on your initiatecheckout and purchase page?

**Comment by hassni1** [comment]
Please check the attachment 
https://prnt.sc/sahh9f 
https://prnt.sc/sahhsg

**Comment by hassni1** [comment]
Please check the attachment 
https://prnt.sc/sb33j3
https://prnt.sc/sb33yn

How to fix missing value parameters ( Partner Integration Opencart ) 

Best Regards.

**Comment by shue249** [comment]
@hassni1 Can you share with us your webstore URL?

**Comment by hassni1** [comment]
https://www.qmart.pk/

**Comment by hassni1** [comment]
@shue249 No response on last reply

**Comment by shue249** [comment]
@hassni1 
1. From your screenshot, the InitiateCheckout is setup via EventSetupTool instead of through the plugin.
![image](https://user-images.githubusercontent.com/11957585/81624419-aa00c000-9428-11ea-88b3-fe6446498eea.png)

2. Are you using 3rd party checkout modules or SEO modules? We access the checkout page on your website and found that the pixel is not firing. This is usually the case when 3rd party checkout modules are used or SEO modules are used. If you have developer resources, this is the code pointer where you can make changes so that the InitiateCheckout and Purchase pixel events can be fired.

InitiateCheckout - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L162

Purchase - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/catalog/controller/extension/facebookeventparameters.php#L128

**Comment by shue249** [comment]
We will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by Khnaz35** [comment]
I am also getting this error 
![image](https://user-images.githubusercontent.com/43812103/105627105-950d7500-5e6f-11eb-9527-81d755e7d534.png)

![image](https://user-images.githubusercontent.com/43812103/105627080-77401000-5e6f-11eb-8f35-45d7798f1815.png)

It say's i am sending it both way with pixel and API, but it is not true i have pixel install before but then i deleted from website and use only plugin for OC
