### ISSUE TITLE
Extension: Facebook for OpenCart (ID: 32336)

### ISSUE THREAD

**Issue by jvteam20** [facebookincubator/Facebook-For-OpenCart#390]
Dear Team,
We would like to use the  Facebook Business Extension v3.0.0 ( Facebook for OpenCart ) in our opencart portal. 
We are using vqmod (2.6.4). Few of the codes are already there in vqmod. Another important change is that, we changed the admin folder name using vqmod. I was reading through the Facebook for OpenCart installation guide ( https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md ) . It was mentioned in the document that VQMOD installation is NOT supported. So, if we install the extension, would our portal work properly ? Is there any alternative way to install the extension. Kindly let us know.
Thanks and regards,
Jonvoh Team

**Comment by shue249** [comment]
@jvteam20 

1. Our plugin is vqmod compatible, the steps to install will still be via the Extension installer. 

2. The renaming of admin folder is a larger problem. There are few code references where we are relying on admin folder. If you have access to developer resources, you can consider making the code changes on your website directly to test if it will work. Do note that, we have yet to test this out on our development environment, so it is highly recommended to test this on your dev setup rather than the actual production.

This is a search for all admin references in the codebase - https://github.com/facebookincubator/Facebook-For-OpenCart/search?p=1&q=admin&unscoped_q=admin

These are the 2 key areas where you need to change from "admin" to your own folder name
1. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/8ce369a7917b1cb513448f21e23cecea4ba539b6/upload/admin/controller/extension/facebookadsextension.php

2. https://github.com/facebookincubator/Facebook-For-OpenCart/blob/8ce369a7917b1cb513448f21e23cecea4ba539b6/install.xml

**Comment by jvteam20** [comment]
Hi shue249,
Thank you for the reply. It is really helpful.
Regards

**Comment by shue249** [comment]
@jvteam20 One correction. I meant to say to make changes to the plugin files and then zip up into ocmod.zip extension again and use the new zip package to install on your OpenCart website. Do take note that the zip package must NOT have any root folder else the installation will complain of errors.

We will be closing out this ticket, feel free to reach to us if you have further questions.
