### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by memopalomas** [facebookincubator/Facebook-For-OpenCart#418]
Hello, I installed the plugin without problems but in the panel where admin shows me some errors in red, I did what it mentioned but I can't get them removed, also if I configure a store, at the end of the process "An error occurred when creating facebook business extension setup. {"success": true, "Pixel_id_number", "installed: true"} "
 
In addition to this extension, I have activated another one of "Facebook Pixel Conversions + Event Tracking". Do you think this will conflict? I tried to deactivate it but the problem was perceived.

the open cart version are 3.0.2.0

**Comment by dtying** [comment]
Hi @memopalomas , I don't think there's a conflict. 
The msg means there's an error in FBE installation. Could you share your webstore_url with us? So that we can check any exception in our backend.

**Comment by fabricioventura** [comment]
Me too!
I was using version 2.1.3, and it worked normally.

After upgrading to version 3.0.1 I was unable to make the connection, when I click "continue with my user" on the initial configuration screen, it displays the same message as the pixel above. It is even a pixel message that we have already removed from our Business manager.

**Comment by fabricioventura** [comment]
If I try to restart the configuration, I can choose my business manager, and when I proceed to choose the page, it is not possible to select! The following error appears:

New admins require approval before linking a Page to a Business Manager.

However, these same data were used in version 2.1.3, even if I downgrade, everything works normally with this data.

What has changed in the new version that I started to have these problems?

at this point I had to go back to version 2.1.3 in order to use the plugin.

my log:

2020-07-15 12:11:39 - Facebook Ads Extension version = 3.0.1
2020-07-15 12:11:39 - OpenCart version = 2.3.0.2
2020-07-15 12:11:39 - PHP version = 7.0.33
2020-07-15 12:11:39 - Verifying Availability of Facebook Ads Extension Settings Availability
2020-07-15 12:11:39 - Pixel ID = true
2020-07-15 12:11:39 - Pixel use PII = true
2020-07-15 12:11:39 - Page ID = true
2020-07-15 12:11:39 - System User Access Token = false
2020-07-15 12:11:39 - Messenger plugin = false

**Comment by yao-tx** [comment]
Hi @memopalomas @fabricioventura 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336) or from [GitHub Latest Release](https://github.com/facebookincubator/Facebook-For-OpenCart/releases/latest). 

We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow one of the following:
* Quick installation guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart)
* Detailed step-by-step guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#plugin-installation).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
