### ISSUE TITLE
Wrong product links/no images when opencart is in a subdirectory

### ISSUE THREAD

**Issue by 1istbesser** [facebookincubator/Facebook-For-OpenCart#421]
The shop is in a subdirectory like  shop.com/london, the correct link for any product would be something like: https://shop.com/london/index.php?route=product/product&product_id=66684

However, the links fetched are like https://shop.com/londonindex.php?route=product/product&product_id=66684

Basically missing a "/".

Same for the image links which is why no image has been fetched.

How can I go about fixing this? Is it something from the extension itself or an internal opencart issue from htaccess?

I thought about adding a rule in htaccess or something for a temporary fix, but I'm not sure what that rule might look like.

**Comment by dtying** [comment]
Hi @1istbesser, here's the code related: https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L162-L173

**Comment by yao-tx** [comment]
Hi @1istbesser 

I believe this is because the URLs set in your OpenCart `config.php` file is wrong. The URLs set in `config.php` should end with a slash ("/").

Anyway, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
