### ISSUE TITLE
How to get a feed link in Facebook-For-OpenCart?

### ISSUE THREAD

**Issue by nab0306** [facebookincubator/Facebook-For-OpenCart#424]
Please, help with problem. 
How to get a feed link (url) in the Facebook-For-OpenCart application so that it can be specified in the catalog (data source) for the planned load of products?
![image](https://user-images.githubusercontent.com/66925441/84606721-29aefe00-aeb1-11ea-9ec5-7d36add7a0e3.png)
![image](https://user-images.githubusercontent.com/66925441/84606726-316ea280-aeb1-11ea-93bd-0ad9af744afe.png)

**Comment by dtying** [comment]
Hi @nab0306 , it's your 'HTTP_CATALOG/index.php?route=extension/facebookfeed/genFeedNow' for real-time generation, or 'HTTP_CATALOG/index.php?route=extension/facebookfeed/genFeed' for a cached version.

**Comment by nab0306** [comment]
Hi,
I entered the address and was denied access.
writes:

Access is denied!
You do not have permission to access this page. If you need one, contact your administrator.

But I am the administrator.

What should I do?

![image](https://user-images.githubusercontent.com/66925441/84777386-308d5c00-afea-11ea-8672-470d86c76078.png)

**Comment by nab0306** [comment]
Sorry, forgot to write. I have the old version of the Facebook Ads Extension 2.0.2 plugin installed.

**Comment by nab0306** [comment]
where to see the value of HTTP_CATALOG?

**Comment by TyrannosaurHex** [comment]
> where to see the value of HTTP_CATALOG?

config.php in your Opencart install directory.

**Comment by nab0306** [comment]
![image](https://user-images.githubusercontent.com/66925441/85023370-4e3efa80-b17d-11ea-9be6-5b9bc8813d35.png)


I do not see

**Comment by nab0306** [comment]
There is no HTTP_CATALOG in config.php file in opencart root directory, but it exists in /admin/config/config.php file. Is this correct?
![image](https://user-images.githubusercontent.com/66925441/85027453-9dd3f500-b182-11ea-85dd-30baeb077c3e.png)

**Comment by yao-tx** [comment]
Hi @nab0306 

Yes, it should be `HTTP_SERVER` or `HTTPS_SERVER` instead of `HTTP_CATALOG` as `HTTP_CATALOG` is only used in admin and not for the frontend.

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.2) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

For the latest version (version 4.0.0 and above), please use the following feed URL:
- For OpenCart version 2.0.x to 2.2.x:
    - HTTPS_SERVER/index.php?route=module/facebook_business/genFeed
- For OpenCart version 2.3 to 3.x.x and above:
    - HTTS_SERVER/index.php?route=extension/module/facebook_business/genFeed

Simply replace HTTPS_SERVER with 'https://missdm.com' in your case.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
