### ISSUE TITLE
[object Object] message when trying to connect my shop with FB

### ISSUE THREAD

**Issue by thgear** [facebookincubator/Facebook-For-OpenCart#429]
I've got connectivity issue too.
![image](https://user-images.githubusercontent.com/67207329/85211790-4c2f9400-b355-11ea-8c8f-03b21dd67f2f.png)

my web-shop is under OC 3.0.3.2 with Journal 3.0.64

Please assist me....

**Comment by dtying** [comment]
Hi @thgear , it basically means your FBE installation failed. 
Could you share your webstore_url so that we can troubleshoot?

**Comment by thgear** [comment]
https://thgear.eu

**Comment by tomeda** [comment]
I face the same issue website is https://nuxta.bg

**Comment by tomeda** [comment]
I had to install extension version 2.2.1 to get it to work.

**Comment by petarstojkovik** [comment]
I'm experiencing the same issue. OC 3.0.3.3 and Journal theme 3.0.46. In addition, I get the following text:

 We have detected the Facebook pixel is not correctly setup in your web store site. You can try these below steps to fix the problem.
1. Ensure that you have given read+write permissions to the admin, catalog and system folders on your OpenCart webserver
2. Ensure that you have Refresh the modifications, View steps
3. For OpenCart 3.x, ensure that you have disabled the theme and SASS cache, View steps
4. For OpenCart 3.x, ensure that you do not have modifications to the header design, View steps

YES, I made sure I followed every step in the installation guide. YES, I checked 1, 2, 3 and 4, all good, but the issue is still there.

I'll uninstall the module since it's obviously still work in progress.

**Comment by leustean13** [comment]
Hello, I have the same issue after installing this module.
I use php 7.3, opencart 3.0.3.3, journal theme 3.0.46. Could you please assist me with this issue? Thanks

**Comment by thgear** [comment]
Is there any progress with that issue? Almost a month and there is no any update?

**Comment by dtying** [comment]
3.1.0 release fixed [Object object] error.
