### ISSUE TITLE
Cant access dashboard 

### ISSUE THREAD

**Issue by qprod74** [facebookincubator/Facebook-For-OpenCart#450]
Got this message after install:

Warning: require_once(/home/qprod/domains/qprod.se/public_html/vqmod/vqcache/vendor/autoload.php): failed to open stream: No such file or directory in /home/qprod/domains/qprod.se/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8

Any idea what to do ? 
Thx.

**Comment by dtying** [comment]
Hi @qprod74, I'm not sure how vQmod handles the module management, but you can check if the file exists at the given path or not.
Without vQmod, the file should be found under /system/library/facebookcommonutils.php

**Comment by petarstojkovik** [comment]
I'm experiencing the same issue. Can't access the admin dashboard.

[27-Jul-2020 12:28:30 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/XXXXXXXX/public_html/vqmod/vqcache/vendor/autoload.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/XXXXXXXX/public_html/vqmod/vqcache/vq2-system_library_facebookcommonutils.php on line 8

**Comment by qprod74** [comment]
> Hi @qprod74, I'm not sure how vQmod handles the module management, but you can check if the file exists at the given path or not.
> Without vQmod, the file should be found under /system/library/facebookcommonutils.php

The file exists in /system/library/facebookcommonutils.php , I uninstalled and installed again, but same problem, I also tried to unzip and upload through ftp  , but same problem .
Thanks

**Comment by ventienda** [comment]
@petarstojkovik @qprod74 @dtying Hi, guys! 
SAME PROBLEM!!! I use OC 3.0.3.2.

I set to 0 the status value on my database (Modification table). Then, I deleted all files and folders in: "system/storage/modification" and "vqmod/vqcache" BUT I couldn't get my access (admin panel). 

Who can help us?

**Comment by qprod74** [comment]
> @petarstojkovik @qprod74 @dtying Hi, guys!
> SAME PROBLEM!!! I use OC 3.0.3.2.
> 
> I set to 0 the status value on my database (Modification table). Then, I deleted all files and folders in: "system/storage/modification" and "vqmod/vqcache" BUT I couldn't get my access (admin panel).
> 
> Who can help us?

Well , after uninstalled the Facebook Ads integration Version 3.1.0 , my dash is back to normal again, I am waiting for a solution / bugfix or whatever causes the problem . Try to delete /system/library/facebookcommonutils.php if you couldnt enter dash (admin) maybe it helps

**Comment by ventienda** [comment]
@petarstojkovik @qprod74 @dtying Hello, again!

Did Anyone fix this issue?

**Comment by petarstojkovik** [comment]
> @petarstojkovik @qprod74 @dtying Hello, again!
> 
> Did Anyone fix this issue?

I guess, no. They even removed Facebook for Opencart extension from Opencart's Marketplace: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336

If you visit the link you will get Error 404: Page Not Found.

**Comment by qprod74** [comment]
Hi , I don't think there is any fix yet , I removed it from my store until it is fixed . 

Sent from my iPhone .
Best regards

**Comment by qprod74** [comment]
Hi , @TyrannosaurHex , I tried your solution unfortunately no difference for me , but I will check the parameters one more time.
Thanks

**Comment by konstantinosbotonakis** [comment]
Here is the solution you guys need. 
[https://github.com/facebookincubator/Facebook-For-OpenCart/pull/480/commits/63b1f1e00acaf39f1f8953d2278a304079d223f8
](https://github.com/facebookincubator/Facebook-For-OpenCart/pull/480/commits/63b1f1e00acaf39f1f8953d2278a304079d223f8
)
I posted this pull and I hope they will include it, into their next version. It happens only if vqmod is installed.

**Comment by haxcop** [comment]
> Here is the solution you guys need.
> [https://github.com/facebookincubator/Facebook-For-OpenCart/pull/480/commits/63b1f1e00acaf39f1f8953d2278a304079d223f8 ](https://github.com/facebookincubator/Facebook-For-OpenCart/pull/480/commits/63b1f1e00acaf39f1f8953d2278a304079d223f8)
> I posted this pull and I hope they will include it, into their next version. It happens only if vqmod is installed.

This Helped! Thanks!

**Comment by qprod74** [comment]
That helped :)
Many thanks


Den sön 27 sep. 2020 kl 12:19 skrev Carlos Lozada <notifications@github.com

**Comment by becharaSfeir** [comment]
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/450#issue-665825470

if any one facing this problem again 
go to /system/library/facebookcommonutils.php and edit the file and stop // require_once __DIR__ . '/vendor/autoload.php';
i think this is a bug, 
your problem will be solved , after this you will have access to the admin panel,

**Comment by yao-tx** [comment]
Hi @qprod74 @petarstojkovik @ventienda @TyrannosaurHex @becharaSfeir

This issue happens because the older version of the FBE plugin (v3.1.2 and below) uses the current directory for their require_once calls. This issue has been resolved in the latest version of the FBE plugin as we are using predefined constants in the OpenCart `config.php` file in our require_once calls. 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin and improved the plugin. Along with the issue mentioned here, we've resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
