### ISSUE TITLE
[BUG]NEED HELP PLEASE

### ISSUE THREAD

**Issue by Laurent3006** [facebookincubator/Facebook-For-OpenCart#465]
Hello, i have this message when i want connect open cart to my new facebook account. 

Administrator authorization required
You do not have permission to change these settings. Contact the E 100 Business Manager administrator to gain access.

The E100 it's an old account and i can't connect on it, when i log on the app i log with my new account, but at the second step this message appear and the E100 account it's not linked on the new. I don't understand

**Comment by yao-tx** [comment]
Hi @Laurent3006 

This is because you will require to be logged into a Facebook account that has admin access to the Business Page you've previously connected your website. For these issues, it is better for you to contact Facebook Business Support directly as this isn't an issue with the Facebook Business Extension plugin for OpenCart, and is rather an issue with your account.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
