### ISSUE TITLE
[BUG] We have detected missing files for Facebook Ads Extension

### ISSUE THREAD

**Issue by ar-Tony** [facebookincubator/Facebook-For-OpenCart#469]
**Webstore Url**
https://tad.sa/

**FBE plugin version**
3.1.0

**OpenCart version**
2.3.0.2

**Describe the bug**
after installed the plugin when I try to open it from main admin panel I got :
There are problems with the installation of the Facebook Ads Extension.
We have detected missing files for Facebook Ads Extension. Please enable read, write and execute access permissions for these files and folders.

**To Reproduce**

**Screenshots**
![FB](https://user-images.githubusercontent.com/63264986/91712108-c5d2d200-eb8f-11ea-85e8-2b5fce2ee815.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox

**Additional context**

**Comment by konstantinosbotonakis** [comment]
The problem is that the code has hardcoded "admin" folder mentions in the code. As your eshop and other opencart eshops don't have the default "admin" folder and they change the name to something else unique, you will need to do some changes in order to make it work.

- Download the ocmod.zip file to your local disk.
- Unzip file.
- Open upload/admin/controller/extension/module/facebookadsextension_installer.php
- Find all **admin/** and replace it with your folder's name, for example **myfolder/**
- Save changes. Now open file: upload/admin/controller/extension/facebookadsextension.php
- Repeat the process: Find all **admin/** and replace it with your folder's name, for example **myfolder/**
- Save changes. 
- Now upload all files to your OpenCart's root folder. 
- Remember to upload the files from admin folder to your admin folder.

You're ready.

**Comment by yao-tx** [comment]
Hi @ar-Tony,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The new plugin does not require OCMOD or any modifications to its directories if you have a custom admin folder name as it is installed through OpenCart's Extension Installer. 

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
