### ISSUE TITLE
The checkout page can't be reached [BUG]

### ISSUE THREAD

**Issue by Superstar18** [facebookincubator/Facebook-For-OpenCart#474]
**Webstore Url**
ICONICUL.RO

**FBE plugin version**
310
**OpenCart version**
3.0.2.0

**Describe the bug**

Hi,

After installing the module and setting it up, the website is working find except when we try to access the checkout or cart page.. You can see a screenshot here:
https://prnt.sc/uej7tj

After i uninstalled the settings, everything is working fine again.

Could you please check? I saw there are also 2 people that have the same issue but they added the report 9 days ago so that's a very long time to not have the pixel set up. I hope you will consider my report as fast as possible so we could find a solution.

This issue is happeing on all browsers i checked. Also checked from other devices.
I've installed the module corectly, refreshed modifications and so on.

Thank you!
Marius

**Comment by PapaIce786** [comment]
Hey Marius, Hi @facebookincubator.

I've got the same problem. My FB Pixel has been down for a week now. 
I'm running opencart Version 3.0.3.0 with Journal 3 and Letcms Multivendor plugin. Checkout cannot be reached with module installed. 
Im losing 2 revenue streams now, Instagram and Facebook.. Kinda Frustrating.

My website is deal-emporium.com if you need to check it out 

Cheers 
Zain

**Comment by Superstar18** [comment]
Hi @PapaIce786 
For a quick fix i uninstalled the updated version and installed Plugin Version: 2.1.10. You can find it here with all the old plugins. Probably you should install the one you had last time untill this update.

https://github.com/facebookincubator/Facebook-For-OpenCart/releases

**Comment by CheckoutPage** [comment]
I'm having the same problem, as well.  My checkout page broke after installing the Facebook for Opencart extension.  I uninstalled the extension and it worked again.  
Opencart version: 3.0.3.2
Facebook for opencart extension version: 3.1.0 

How do I fix this problem in the extension? I have been checking the comments and several people have had this complaint. Yet I have not seen any definite answer yet.  Down-grading the facebook extension to version 3.0.1 did not work for me because after uploading and installing the ocmod zip file, I could not find the button that says 'Manage Settings' so I could not use the extension.  (Was I supposed to FTP/upload the contents of the source codes zip folder too in order to get the older version to work?) 

Anyway, someone please help me solve this problem. 
Thanks.

**Comment by Superstar18** [comment]
@CheckoutPage you have the settings in opencart tabs, the first one, named "facebook business extension". You can apply the quick fix because i see that the issue is waiting for a solution for 2 weeks already.

**Comment by CheckoutPage** [comment]
You'd have to walk me through how to implement the quick fix you speak about, as I've already tried out one quick fix that was suggested here, which did not work for me.  I uninstalled the latest version 3.1.0, and installed the previous version 3.0.1, but was unable to go forward because the 'Manage Settings' button disappeared.  Don't know what I did wrong there.  I installed v. 3.0.1 using the Opencart Installer to upload the ocmod.zip file, and that's all I did.  Was I supposed to do something else after that? 

While waiting for the resolution of the problem with the FB extension v. 3.1.0, I need someone to walk me through how to install the older FB extension v. 3.0.1 on my opencart 3.0.3.2 website. Step-by-step, to get it to work.  Thanks.

**Comment by Superstar18** [comment]
That's all i've done. Uninstalled from opencart the module that doesn't work. Refresh modifications.
Installed the old module that worked till i've made the update and clicked again refresh modifications.

PS: Untill uninstalling, try to disconnect the store from the module's settings. I think i've done that also.

**Comment by CheckoutPage** [comment]
Thanks for trying to help with this but I don't have a previously working module as this is a brand new opencart website.  Where do I find the instructions on how to properly install the older Facebook for Opencart Extension version 3.0.1. 
It seems like just installing the ocmod.zip file was not enough. 

FBE installation website only talks about the newest version.

**Comment by Superstar18** [comment]
@CheckoutPage The plugin version that works for me is 2.1.10. You can try this one till they solve the actual problem.

**Comment by Superstar18** [comment]
Hi @CheckoutPage. I'm talking with a developer from facebook at this topic about the same issue: https://github.com/facebookincubator/Facebook-For-OpenCart/issues/470

Could you send there the error log? I don't have this version of the module installed and i can't send the error log so he could check the problem.

**Comment by dmasterz** [comment]
please see my post on #470 for a temporary workaround.

**Comment by yao-tx** [comment]
Hi @Superstar18 @PapaIce786 @CheckoutPage @BrokeBoysGameStudio 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The error with checkout page is a known bug with the previous versions of the FBE Plugin and has been resolved in the latest version.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
