### ISSUE TITLE
FB shop Displayed out of stock and discontinued products 

### ISSUE THREAD

**Issue by hassni1** [facebookincubator/Facebook-For-OpenCart#499]
**FBE plugin version**
Plugin Version: 3.1.0

**OpenCart version**
3.0.2.0

Module sync the all products on fb catalog, all stock statuses in stock, discontinued, pre-order, out of stock and etc. 
i want this module only sync only in stock products, exclude out of stock and sold out items, please guide how to do that.

**Comment by hassni1** [comment]
No Response yet

**Comment by dtying** [comment]
Hi @hassni1, thanks for reporting the issue. Can you share us a screenshot of your products showing those statuses which you don't want to be synced. That can help us to reproduce the same issue in our end. Thanks!

**Comment by hassni1** [comment]
Here is the screenshot 
https://prntscr.com/vbqo1v
https://prntscr.com/vbqo77

**Comment by hassni1** [comment]
Admin panel screen shot 
https://prntscr.com/vbshh0

**Comment by hassni1** [comment]
Hi @dtying please check the screen shot

**Comment by hassni1** [comment]
@dtying waiting for the response

**Comment by hassni1** [comment]
@dtying waiting

**Comment by hassni1** [comment]
@dtying no response 👎

**Comment by hassni1** [comment]
@dtying Please Reply , I think i have to uninstalled the module

**Comment by djlaserman** [comment]
using OC 3.0.3.6 and FBE 3.1.1 and this issue has always been there. I've reported it before in these seamless issue threads.

Even Facebook itself doesn't have programmers good enough to fix and improve small issues with their catalogue feeds as one cannot exclude certain listings of products hand picked by simply adding to a list so as to avoid their issue of old products that cannot be removed... they just show up with wrong data and pricing about a 100 to 200 random such items that are added to a product feed from nowhere. Deleting products is one by one and they come back when refreshing the feeds making it harder to get to the redundant erroneous records... I suspect it's this plugin as well because it creates the feed with the crazy data

![opencart_fbe_stock_availability_bug01](https://user-images.githubusercontent.com/41134053/101282694-39176000-37df-11eb-8c4b-a70374721648.png)

**Comment by djlaserman** [comment]
> @dtying Please Reply , I think i have to uninstall the module

Well, it will still work the same because this issue was there even in previous versions. So do uninstall and perhaps look for a paid third party plugin (and beware of those as they mostly mess up the store core files and things get wonky, especially if using a third party theme as well, it gets complicated quickly). Just always have a full backup, files and database, before tinkering a lot.

On my end, I'll fork the project and investigate this. If I manage to get it to behave, I'll come back with the link to the working branch 🌿 if I don't get the time... we'll both need to wait for a genius out there to do justice with the code.

**Comment by yao-tx** [comment]
Hi all,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!

**Comment by yao-tx** [comment]
Hi @djlaserman @hassni1 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
