### ISSUE TITLE
Problem with opencart module

### ISSUE THREAD

**Issue by papko7** [facebookincubator/Facebook-For-OpenCart#501]
Hello I tried to install facebook ads extension. After install and opening module I am getting this error in console. Webpage can not loading I waited for a while. Could you help me what to do ?
[](url)
<img width="1440" alt="Snímka obrazovky 2020-11-01 o 17 42 25" src="https://user-images.githubusercontent.com/37934869/97808862-a4fb2b80-1c69-11eb-8f91-8dc46b83ffe0.png">
<img width="1172" alt="Snímka obrazovky 2020-11-01 o 17 42 35" src="https://user-images.githubusercontent.com/37934869/97808865-a88eb280-1c69-11eb-8f32-efc4a266aa38.png">

**Comment by dtying** [comment]
Hi @papko7 , there shouldn't be any 'Resync' button shown in the latest version, and it implied that your module installation process is not correct because the cache is not refreshed. Please strictly follow the installation guide to perform the installation process. You can find it in the repo home page. Thanks!

**Comment by papko7** [comment]
awesome thanks
