### ISSUE TITLE
AddToCart and Event ID Parameter bug

### ISSUE THREAD

**Issue by papko7** [facebookincubator/Facebook-For-OpenCart#503]
Hello
I am getting two error in my pixel 
1. ISSUE
You're sending AddToCart events through both your pixel and the Conversions API, but they're not being deduplicated because an event_id parameter hasn't been received for this event. Without an event_id, your AddToCart events will be double counted because they can't be deduplicated.
This may cause issues with the measurement of your events as well as the attribution and delivery optimization of any ad campaigns that are optimizing for this event.
SOLUTION
Add an event_id parameter to your AddToCart event within your server payload. You can use the Payload Helper tool on the Facebook for Developer's site to validate that your payload is set up correctly.
2. ISSUE
Your server is sending the event_id parameter for your AddToCart event inside the custom_data field of your payload. Event_id is invalid unless it's sent as a top level data field, in the same section as your event name.
This may cause issues with the attribution and delivery optimization of any ad campaigns optimizing for this event.
SOLUTION
Remove the event_id parameter from the custom_data field section of your payload and add it as a top level data field. You can use the Payload Helper tool on the Facebook for Developer's site to validate that your payload is set up correctly.

Could you please help me with that ?
Thanks

**Comment by dtying** [comment]
Hi @papko7, thanks for reporting the bug! It has been fixed in the latest release: https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v3.1.1

**Comment by papko7** [comment]
Awesome thanks

**Comment by Gen-Dub** [comment]
Hi! I got the same issue as @papko7... 

(2-ISSUE
Your server is sending the event_id parameter for your AddToCart event inside the custom_data field of your payload. Event_id is invalid unless it's sent as a top level data field, in the same section as your event name.
This may cause issues with the attribution and delivery optimization of any ad campaigns optimizing for this event.
SOLUTION
Remove the event_id parameter from the custom_data field section of your payload and add it as a top level data field. You can use the Payload Helper tool on the Facebook for Developer's site to validate that your payload is set up correctly.)

... **but with my PageView event**! Since yesterday. Can someone help me please?! I got a lot of Ads running :/

Thanks in advance!
