### ISSUE TITLE
Friendly path when click on button Payment on site from Fanpage

### ISSUE THREAD

**Issue by tuananh8127** [facebookincubator/Facebook-For-OpenCart#51]
I want friendly path when click on button Payment on site from Fanpage
View image: https://imgur.com/a/SgLsRNu
Thanks

**Comment by shue249** [comment]
Thank you for your feedback! May I know what is your web store URL?

**Comment by tuananh8127** [comment]
> Thank you for your feedback! May I know what is your web store URL?

My store url
https://www.facebook.com/pg/newsshares/shop/?ref=page_internal
Thanks.

**Comment by rutar111** [comment]
Hi, did you fix that problem with SEO urls?

**Comment by shue249** [comment]
@tuananh8127 We have evaluated on supporting SEO url for the products on Facebook. Due to the underlying database structure of how the SEO urls are stored (SEO data are stored on separate tables url_alias or seo_url, depending on the OpenCart version), there will be a decrease in the performance when performing the initial catalog sync to Facebook. This may cause extra load on the database server, especially for users who have a large number of products.

In view of this, we will deprioritize this feature and mark it as nofix.

However, if you have development resources, you can take up to change the plugin codes yourself. The area to change the plugin code will be at these lines - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L154-L156
You may want to consider looking at the Opencart default url.php and seo_url.php class to understand how OpenCart generates the SEO url.

https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/system/library/url.php#L37
https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/catalog/controller/startup/seo_url.php#L45
