### ISSUE TITLE
Translate notification bar

### ISSUE THREAD

**Issue by doviis** [facebookincubator/Facebook-For-OpenCart#514]
Hello,
How to translate cookie notification ?  

" Our Site Uses Cookies
 
By clicking Agree, you agree to our terms of service, privacy policy and cookies policy."

Where is the file with that string? I will translate straight from file.

**Comment by yao-tx** [comment]
Hi @doviis 

Sorry, this might be a little too late but for the Facebook Business Extension version 3.1.2 and below, the texts are added through the OCMOD script. Since OpenCart stores OCMOD scripts in the database in the modification table, you will have to translate it through the database or through a 3rd party extension that allows you to modify modification scripts from your OpenCart admin.

Anyway, the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) is available on [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, made improvements to the plugin and resolved most of the bugs and issues that users are having with the previous versions. This should resolve the issues you are having.

For the new FBE plugin (version 4.0.0 and above), if you are using OpenCart version 2.3 and above, you can easily translate the text in 'facebook_business.php' located in 'catalog/controller/extension/module'. Otherwise, for OpenCart version 2.0.x to 2.2.x, translation has to be made to the OCMOD script as well, similar to the method described above.

That being said, if you are still encountering any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
