### ISSUE TITLE
[BUG] ?? Variations not listed

### ISSUE THREAD

**Issue by DaveRiba** [facebookincubator/Facebook-For-OpenCart#527]
**Webstore Url**
Your webstore Url
harbor-sales.com
**FBE plugin version**
Version of FBE plugin
3.1.1

**OpenCart version**
Version of OpenCart
3.0.3.6
**Describe the bug**
Installed FBE. Uploaded the Catalog. Each unique product shows up.  But some products have Variations listed (White, Red, Blue,. etc)  Only the base product shows up.  No variations
**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows Server 2019
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Comment by yao-tx** [comment]
Hi @DaveRiba 

Unfortunately, as OpenCart does not support Product Variants and only has product options, the FBE plugin is unable to pull options as variations since options do not have a unique ID or SKU in OpenCart.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
