### ISSUE TITLE
Can I update to new extension version without losing event history

### ISSUE THREAD

**Issue by kanjuo** [facebookincubator/Facebook-For-OpenCart#544]
Is it possible to update to the latest version of this MODULE without losing events history, there is a minimum events required by facebook before you can run campaigns aimed at optimizing for that event

I really dont want to lose that history as money has been invested towards them

**Comment by dtying** [comment]
Hi @kanjuo , your pixel event history won't be lost after upgrading the extension. You can always check your event history by using [Facebook Events Manager](https://www.facebook.com/business/help/898185560232180?id=1205376682832142).

**Comment by kanjuo** [comment]
This is what it says here:

"Remove all existing pixel implementations from the website. Duplicate pixel events may be fired if there are existing pixel implementations.

"

**Comment by kanjuo** [comment]
Also must i delete the previous 'facebook_ads_extension.ocmod.zip' files? because when i use the installer it uploads indefinitely, im using opencart Version 3.0.2.0

**Comment by yao-tx** [comment]
Hi @kanjuo,

What "Remove all existing pixel implementations from the website" means any pixel code and/or extensions that might be implementing Facebook pixels on your OpenCart website. This is to prevent pixel events from firing multiple times for one event due to duplication of pixel implementations on your OpenCart website. 

For example, if you already have an extension that is tracking Add to Cart pixel events on your website and you install the Facebook Business Extension, which also tracks Add to Cart pixel events, then each time a customer adds an item to cart, the Add to Cart pixel event will be fired twice instead of once.

It does not mean that your pixel event history will be removed. Your pixel event history is stored with your Facebook Business account and not on OpenCart.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart at [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336).

If you encounter any issues with it, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/) for assistance. Thank you!
