### ISSUE TITLE
discount price is not shown in Facebook catalog - opencart

### ISSUE THREAD

**Issue by egeorgegeorge** [facebookincubator/Facebook-For-OpenCart#549]
Sale / Discount price is not showing in my Facebook Catalog - Opencart , I am using facebook_ads_extension.ocmod official extension. For example real price for now is  old - 2,450.0 - 30% = and new is 1,715.0!
![ewdasdsferw](https://user-images.githubusercontent.com/78765256/107288819-83d28400-6a7d-11eb-80d5-529c185985b9.png)

and on Facebook

![147289520_10220477147343479_5823729649109687567_n](https://user-images.githubusercontent.com/78765256/107288575-1888b200-6a7d-11eb-97fa-f231dfca3ed3.jpg)

I am using discount by categories and not by product, i think that is the problem, but how can i sync it to Facebook catalog, please help. Which file I need to edit?

**Comment by yao-tx** [comment]
Hi @egeorgegeorge,

If you are using a custom extension that is applying discounts to your products, you will have to customise the FBE plugin to retrieve the special prices separately. This is because by default, the FBE plugin will pull the OpenCart specials price ("Special" tab in your admin panel in your product configurations) and use it as Sale price for Facebook Catalog.

That being said, please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

For the new plugin, you should be able to see that the Sale price for Facebook Catalog is set in `facebook_business.php` located in `catalog/controller/extension/module` under the `formatProductDetails` function.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
