### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thorn2rose** [facebookincubator/Facebook-For-OpenCart#557]
**Webstore Url**
https://thorn2rose.com/?fbclid=IwAR1A1keZaJmeJqF8sNrDk0Qkl_raaDWBAEAO1g4Ve7lwxEPquFGjXwWkRdQ
**FBE plugin version**
Plugin Version: 2.1.3

**OpenCart version**
 3.0.2.0

**Describe the bug**
There is an error with Facebook Ads Extension setup
Please contact Facebook via our Github if this error keeps showing

**Comment by ansonf** [comment]
https://drawcookie.linkingcat.com/

My site is same case.

**Comment by yao-tx** [comment]
@thorn2rose   @ansonf  
Hello,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). This should resolve the issues you are having with the current versions.

If you still have any further issues, please feel free to reach out to us via our help desk [here](http://marketinsg.zendesk.com/) so that we can assist you with your issues.

**Comment by yao-tx** [comment]
Hello @thorn2rose @ansonf,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
