### ISSUE TITLE
[BUG] An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.

### ISSUE THREAD

**Issue by ivent** [facebookincubator/Facebook-For-OpenCart#558]
**Webstore Url**
Your webstore Url

**FBE plugin version**
Version of FBE plugin

**OpenCart version**
Version of OpenCart
 3.0.3.6

**Describe the bug**

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

Module version 3.1.2
I cannot finish the final configuration a notification appears with the following error

An error occured while generating system user access token: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.

**Comment by Bulikus** [comment]
I got the same issue. Opencart v. 3.0.3.7

**Comment by yao-tx** [comment]
@ivent  @Bulikus 
Hello,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). This should resolve the issues you are having with the current versions.

If you still have any further issues, please feel free to reach out to us via our help desk [here](http://marketinsg.zendesk.com/) so that we can assist you with your issues.

**Comment by yao-tx** [comment]
Hello @ivent @Bulikus,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users were having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
