### ISSUE TITLE
[BUG] Hello I installed the facebook ad extension now I cant edit or add product

### ISSUE THREAD

**Issue by muraterdogann** [facebookincubator/Facebook-For-OpenCart#559]
FBE plugin version
Plugin Version: 2.1.3

OpenCart version
Version 3.0.3.2

After installing extension from facebook I can't able to edit or add products.

Error log is : Unexpected token "name" of value "" ("end of print statement" expected) in "catalog/product_form.twig" at line 206.

**Comment by yao-tx** [comment]
@muraterdogann 
Hello there,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at OpenCart Marketplace. This should resolve the issues you are having with the current versions.

If you still have any further issues, please feel free to reach out to us via our help desk [here](http://marketinsg.zendesk.com/) so that we can assist you with your issues.

**Comment by yao-tx** [comment]
Hello @muraterdogann,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
