### ISSUE TITLE
There are problems with the installation of the Facebook Ads Extension

### ISSUE THREAD

**Issue by khaledjahmad** [facebookincubator/Facebook-For-OpenCart#561]
Hi guys
There are problems with the installation of the Facebook Ads Extension

1- We have detected these missing database tables for Facebook Ads Extension. Please give the CREATE privilege for your database user.
Please also ensure Facebook Ads Extension module is installed. Access Extensions -> Select Modules from dropdown list -> Click on green install button for Facebook Ads Extension

oc_facebook_product

Please uninstall and reinstall the Facebook Ads Extension after correcting the above 1 step.

opencart Version 3.0.2.0
Extension 2.1.3

**Comment by yao-tx** [comment]
@khaledjahmad 
Hello there,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at OpenCart Marketplace. This should resolve the issues you are having with the current versions.

If you still have any further issues, please feel free to reach out to us via our help desk [here](http://marketinsg.zendesk.com/) so that we can assist you with your issues.

**Comment by yao-tx** [comment]
Hello @khaledjahmad,

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

If you encounter any issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you!
