### ISSUE TITLE
[BUG]Cannot activate messenger plugin in Facebook Ads Extension

### ISSUE THREAD

**Issue by SRSI410** [facebookincubator/Facebook-For-OpenCart#565]
**Webstore Url**
https://shop.srsi.re/

**FBE plugin version**
2.1.4 / 2.2.0 / 2.2.1

**OpenCart version**
3.0.2.0

**Describe the bug**
Cannot activate messenger plugin in Facebook Ads Extension

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Server : Opencart 3.0.2.0 on Debian 10 - OS Client : Windows 10 Pro
 - Browser Mozilla Firefox or Google Chrome
![messenger](https://user-images.githubusercontent.com/82674529/115066901-351feb00-9f01-11eb-8fac-2ce2ae0fea21.jpg)

LOG FILE ----
[Shop SRSI_2021-04-16_18-15-05_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/6327193/Shop.SRSI_2021-04-16_18-15-05_facebook_ads_extension.log)
[Shop SRSI_2021-04-16_18-03-33_facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/6327194/Shop.SRSI_2021-04-16_18-03-33_facebook_ads_extension.log)

@shue249 
@dtying 

Thanks !!
 
**Additional context**
I tried many version of plugin but i can't activate messenger

**Comment by yao-tx** [comment]
@SRSI410 
Hello there,

Please download the latest version (4.0.1) of the Facebook Business Extension plugin for OpenCart at [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). This should resolve the issues you are having with the current versions.

**Comment by SRSI410** [comment]
Hello 

Can you send me a link to download latest version (v4.0.1 - 27/04/21) please ?

Because on this link OpenCart Marketplace only v4.0.0 appears.

Regards,

**Comment by yao-tx** [comment]
Hello,

The latest version 4.0.1 should be available on [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). Please proceed there to download it and perform a re-install if if necessary.

Please reach out to us via our [help desk](https://marketinsg.zendesk.com/) if you have any further issues with the Facebook Business Extension plugin for OpenCart. Otherwise, please contact Facebook Business's support team for issues related to Facebook.
