### ISSUE TITLE
[BUG] how to regenerate feed !!

### ISSUE THREAD

**Issue by istbrq101** [facebookincubator/Facebook-For-OpenCart#572]
Hi I'm trying to regenerate the feed but only 6 products show in the feed 
how to fetch the feed to add all products 
My Opencart website working on Version 3.0.2.0
Thank you

**Comment by yao-tx** [comment]
Hi @istbrq101 

For version 4.0.1 and above, you should be able to clear the existing product feed csv file by clicking on 'Save' at your Facebook Business Extension plugin page in admin.

That being said, you will have to force a re-upload of the catalog from Facebook's side, i.e. from your Facebook Business page under Commerce Management.

On top of that, please note that disabled products will not be exported. Also, please ensure that your product description is not empty and is at least 30 characters long. This is because Facebook's requirement is that products must have a proper description of more than 30 characters. For more information and details, please refer to this link [here](https://www.facebook.com/business/help/120325381656392?id=725943027795860).

If you are still having issues with your Facebook Catalog Feed, please open a ticket with us via our [helpdesk](https://marketinsg.zendesk.com/). Thank you :)

**Comment by istbrq101** [comment]
Thank you so much it's working fine now 
the issue because the description was short less than 30 characters.

**Comment by yao-tx** [comment]
Hi @istbrq101 

Sure, glad that it's working now :) I'll be closing this issue but if you have any further issues, please reach out to us via our [help desk](https://marketinsg.zendesk.com/). Thank you :)
