### ISSUE TITLE
Right format on the product description sent to FB

### ISSUE THREAD

**Issue by rod2k** [facebookincubator/Facebook-For-OpenCart#576]
Hello, how do I send the description from my store to FB Catalog with format, for now my descriptions in fb doesn't have any CR/LR character.

I already tried sending plain text, HTML and Json, nothing works, what's the right way to send the description field to facebook?
![a](https://user-images.githubusercontent.com/23507339/118897794-39587300-b8c8-11eb-82fa-3ca8f4b4c332.png)
![b](https://user-images.githubusercontent.com/23507339/118897790-38bfdc80-b8c8-11eb-9989-cdc3997c4ed9.png)

**Comment by yao-tx** [comment]
Hi @rod2k 

This is because the FBE plugin strips all HTML tags from Product Descriptions before sending it over to your Facebook Catalog. This is a requirement by Facebook, and you can take a look at the requirements and specifications for product descriptions here: https://www.facebook.com/business/help/2302017289821154?id=725943027795860
