### ISSUE TITLE
Facebook business extension version 4.1.1 on opencart 3.0.2.0 multiple menu item on admin page,,[BUG]

### ISSUE THREAD

**Issue by nasirkhalil** [facebookincubator/Facebook-For-OpenCart#582]
I have installed Facebook business extension version 4.1.1 on opencart 3.0.2.0, but when I installed it show on admin menu three times. in product edit page it also show 3 Facebook tabs, attach is images for refrence, I have searching for past 3 hour but no luck can anyone help me on this, i will be very thankfull.

**Comment by yao-tx** [comment]
Hi @nasirkhalil 

It sounds like you might have duplicated events due to multiple installs. Please try uninstalling the extension by clicking the red uninstall button for Facebook Business Extension at Extensions >> Extensions >> Modules, and perform a reinstall again and that should solve the issue you are having.

That being said, if you are still encountering issues, please reach out to us via our [helpdesk](https://marketinsg.zendesk.com/).
