### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by grmironenko** [facebookincubator/Facebook-For-OpenCart#585]
**FBE plugin version**
Version of FBE plugin
Пиксель собирает события только с главной страницы

**Comment by yao-tx** [comment]
HI @grmironenko 

Unfortunately, due to our small team, support is only available in English for the Facebook Business Extension plugin for OpenCart.

If you are encountering issues with the plugin on your OpenCart site, please open a ticket with us via our [helpdesk](https://marketinsg.zendesk.com) in English so that we can look into the issue and resolve it for you.
