### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by marian821** [facebookincubator/Facebook-For-OpenCart#591]
**Webstore Url**![image]
https://sellsell.ro/
**FBE plugin version**
Plugin Version 4.2.0

**OpenCart version**
3.0.3.2

**Describe the bug**
No puchase server event detected. Browser event works right.

**To Reproduce**
finish a order
1. Go to 'website'
2. Make a order

**Screenshots**
![Screen Shot 2021-10-05 at 10 41 03 PM](https://user-images.githubusercontent.com/84157492/136092084-7cae6c40-b659-46be-84b6-33cc7d155efc.png)

**Comment by yao-tx** [comment]
Hi @marian821 

This is usually due to custom checkout pages as the plugin detects the 'checkout/checkout' route by default and is not able to accommodate custom checkout URLs. Please reach out to us via our [helpdesk](https://marketinsg.zendesk.com/) so that we can assist you in resolving this issue.
