### ISSUE TITLE
I installed the latest version 2.1.2 but pixel still does not work on product pages.

### ISSUE THREAD

**Issue by drewnya** [facebookincubator/Facebook-For-OpenCart#61]
_Originally posted by @drewnya in https://github.com/facebookincubator/Facebook-For-OpenCart/issue_comments#issuecomment-439794501_

**Comment by shue249** [comment]
@drewnya Thank you for the feedback, and we really apologies for the inconvenience for the plugin. I will have to dig deeper as the problem may be a different one from the SEO product URL. Pls give us some time to check this out.

https://imocean.com.ua/svitshoti/zhenskie-svitshoti/svitshot-rozhdestvenskij-s-olenjami-belij-ukrs-8823

**Comment by shue249** [comment]
@drewnya Apologies for the long delay in response. We have been looking into the SEO issue with another user. Can we understand if you are using the SEO editor plugin? Will you be able to look into this post and see if you are using similar setup configurations on your website. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/82

If so, can you share with us how are you setting up your configuration, so that we can try to work out a proper fix to be able to cater for your configuration as well.

**Comment by drewnya** [comment]
Hi, @shue249.  I'm not using the SEO editor plugin. This add-on is used to SEO urls [https://github.com/rb2/opencart-seopro](https://github.com/rb2/opencart-seopro)
Addition is already built into this Openсart [https://github.com/ocshop/ocshop/tree/oc-2.3.0.2.1](https://github.com/ocshop/ocshop/tree/oc-2.3.0.2.1)

**Comment by shue249** [comment]
@drewnya Thank you for your feedback. Let us look into this SEO plugin and see if we can make our plugin to be compatible with this.

**Comment by shue249** [comment]
@drewnya 
We have released a latest version of the plugin, v2.1.4 and can be downloaded from OpenCart marketplace or our github. The new version should resolve your issue with SEO URL.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336
https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.4

Can you try out the new version of the plugin and let us know if it helps you.

**Comment by drewnya** [comment]
Everything is working. Thanks.
