### ISSUE TITLE
Directory containing files to be uploaded could not be found!

### ISSUE THREAD

**Issue by ryanstacey** [facebookincubator/Facebook-For-OpenCart#62]
I can't even upload the .ocmod.zip file, every time it tries to upload the loading bar gets half way, goes red and says: Directory containing files to be uploaded could not be found!

**Comment by ryanstacey** [comment]
Seems that if i collapse the 'upload' folder and have admin, catalog and system in the same folder and the other files it can upload. I click continue and do the whole modification refresh but nothing happens. The bar doesn't show up in the menu.

**Comment by ryanstacey** [comment]
Ive tried uploading with FTP, without FTP using the OCMOD iSenseLab. Ive tried changing the install.xml to install.ocmod.xml which someone recommended. Nothing is working. Is there a manual way of uploading it?

**Comment by shue249** [comment]
@ryanstacey Thank you for the feedback. 

Can we understand where  have you obtained the file from? Can you try to get the zip file from https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.2?

From our understanding, the error message "Directory containing files to be uploaded could not be found" is due to the missing upload folder. And the upload folder must be the inside the zip file directory and there should not have any additional sub-folder layer. A common problem we faced earlier was to have a sub-folder layer inside the zip file. Did you unzip the file and then zip up the folder again?

![image](https://user-images.githubusercontent.com/11957585/48873445-d259c080-ee28-11e8-9175-a171e556cd7a.png)

**Comment by ryanstacey** [comment]
Thank you, the problem was no matter where I downloaded the files from it never downloaded it as a .zip its like it automatically extracted the files into a folder on download. So I had to take them out the folder and recompress them. I was using Safari on MacOs for reference.

**Comment by shue249** [comment]
@ryanstacey I believe that the zip file that you re-compressed has a inner sub-folder layer which caused the zip file to fail. Can you try to zip in this method instead?

![image](https://user-images.githubusercontent.com/11957585/48892014-f395cd80-ee77-11e8-8618-49239e7412e0.png)
![image](https://user-images.githubusercontent.com/11957585/48892096-250e9900-ee78-11e8-98cf-08580ec4ed5d.png)

**Comment by ryanstacey** [comment]
Yes this has worked. Thank you.

**Comment by shue249** [comment]
@ryanstacey Nice to hear that this works. We will proceed to close off the ticket, feel free to reopen if needed.
