### ISSUE TITLE
Issue about creating new catalogs thru syncing

### ISSUE THREAD

**Issue by i3kevin** [facebookincubator/Facebook-For-OpenCart#65]
I am running a Facebook page and I had uploaded products manually to catalog which is link to the "Shop" Tab in my Facebook page. 
However, when I develop my opencart site recently and installed the facebook extension, it sync all my opencart products and creates a new catalog. Now on facebook I have two catalogs (some products are duplicated). Is it possible I can delete the old catalog (the one originally on facebook) and replace by the new one (sync from opencart)? also let the new catalog to link up to the "Shop" Tab in Facebook page (which what the original catalog did)?
I have been searching for so long and I cannot find a solution for this.
Thanks so much for the help!

**Comment by shue249** [comment]
@i3kevin Thank you for the feedback.

I agree with your thoughts. Our recommendation is to use the catalog created from the facebook extension plugin, because our extension plugin will automatically sync in products from your opencart webstore into the catalog and Shop tab on Facebook page.

When you install the Facebook Ads Extension, did you select the option to create Page Shop? If you do so, the current Shop will be using the catalog from our plugin extension, so all's good. If you did not do so, I will suggest for you to delete away the settings again and re-do the Facebook Ads Extension again. To delete away the settings, go to the Facebook Ads Extension, and then click on options and click on Delete Settings.

![image](https://user-images.githubusercontent.com/11957585/48873596-b0ad0900-ee29-11e8-9749-f52df81ec88d.png)

![image](https://user-images.githubusercontent.com/11957585/48873702-4a74b600-ee2a-11e8-8765-3f059ad69b23.png)


To remove away your earlier catalog, you can access the catalog, settings and click on Delete catalog. Pls ensure that you have no dynamic ads running that uses this catalog. Or otherwise, you can also let the catalog remain and there will be no harmful consequence too.

![image](https://user-images.githubusercontent.com/11957585/48873758-a0e1f480-ee2a-11e8-96d4-27ab362bb8e4.png)

I hope the reply answers your question, we will be closing out this ticket, but feel free to reopen them if you need it.
