### ISSUE TITLE
Products not syncing version Version 2.0.3.1 OpenCart

### ISSUE THREAD

**Issue by sonia-coelho** [facebookincubator/Facebook-For-OpenCart#66]
hello, so i've already installed the facebook ads extension and did the setup but the thing is when i access the catalog on facebook the diagnosis says i have only 4 products, if i go to products it says that i have 817 products, but when i go to the extension advanced settings it says that i have 2800 products. i tried to resync but nothinf happens. Am i doing something wrong? Does this really sync automatically?

This is my website URL: https://www.clubtek.pt/

**Comment by shue249** [comment]
@sonia-coelho Thank you for your feedback. 

We see that you are having an earlier version of our plugin, v2.0.3, whereby store websites with large number of products may not perform the initial product sync correctly. I will say that the catalog on FB should be incomplete as it should be 2800+ instead of just 800+.

We have released a newer version, v2.1.2, whereby we have addressed this problem. You can download the plugin from https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.2. And you proceed to upgrade the plugin to the newer version (you will need to remove the older 2.0.3 version and install in the newer version). 

After the newer version is installed, you can go to Facebook Ads Extenstion, click on Manage Settings, Advanced options, and click Delete settings. This will allow you to re-setup and perform the initial catalog sync again.

I will proceed to close this ticket, but pls, feel free to reopen the ticket if you still encounter any problems.
