### ISSUE TITLE
Multi language Description and SEO friendly link issue

### ISSUE THREAD

**Issue by rutar111** [facebookincubator/Facebook-For-OpenCart#76]
Hi, as i can see the extension only reads and shows the description of a product from an english tab in opencart 3.0.0.2. We are from Slovenia so we are writing our product description in slovenian tab in OC. Can you fix it, that the extension reads the product data from another tab?

In facebook shop if you clik on check out on website it redirects you to our page, but the link is not SEO friendly it shows the default path index.php?route=product%2Fproduct&product_id=70

And in our facebook shop if we go to settings and set "Use checkout Urls", the button in product just redirects you to product page not into cart as it should.

Can this be solved?

**Comment by shue249** [comment]
@rutar111 Thank you for the feedback. 

1. Let us look into the product description

2. For the checkout URL, we will be looking at it. In the meantime, it should not affect your sales as consumers are able to reach to your page.

3. We are not supporting for the direct adding of products to cart, as we are unable to cater for support for the product variant options.

**Comment by rutar111** [comment]
When could we expect the fix?
The problem for the un friendly SEO url is that we are not getting traffic to the correct urls, and is not boosting our position on google like it should, it would be great if you could fix that first, its much more important as descriptions etc..

Regards

**Comment by shue249** [comment]
@rutar111 We have evaluated on supporting SEO url for the products on Facebook. Due to the underlying database structure of how the SEO urls are stored (SEO data are stored on separate tables url_alias or seo_url, depending on the OpenCart version), there will be a decrease in the performance when performing the initial catalog sync to Facebook. This may cause extra load on the database server, especially for users who have a large number of products.

In view of this, we will deprioritize this feature and mark it as nofix.

However, if you have development resources, you can take up to change the plugin codes yourself. The area to change the plugin code will be at these lines - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L154-L156
You may want to consider looking at the Opencart default url.php and seo_url.php class to understand how OpenCart generates the SEO url. 

https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/system/library/url.php#L37
https://github.com/opencart/opencart/blob/0fdfc437c9be81a712e8cd6358612c3bb7f0c356/upload/catalog/controller/startup/seo_url.php#L45

**Comment by shue249** [comment]
@rutar111 Coming back to this ticket. If you wish to make changes to the default language to be used on Facebook catalog and page shop, you can refer to this post on making code changes to the plugin directly to make these changes. 

https://github.com/facebookincubator/Facebook-For-OpenCart/issues/133#issuecomment-521123832

**Comment by yao-tx** [comment]
Hi @rutar111 

Please download the latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.1) from [OpenCart Marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32336). We have revamped the entire plugin, improved the plugin and resolved most of the bugs and issues that users are having with the previous versions.

The latest version of the Facebook Business Extension plugin for OpenCart (version 4.0.0 and above) supports SEO friendly URLs now, provided that SEO URL is enabled and supported in your OpenCart website. 

Also, just a quick explanation on how the new version supports SEO URLs, the previous versions (version 3.1.2 and below) somehow hardcoded the product URL and appends the product ID to the hardcoded product URL (i.e. `index.php?route=product/product&product_id=`)  instead of simply using the OpenCart URL function (i.e. `$this->url->link()` function). Therefore, the new version utilises the OpenCart URL function which will automatically change it into SEO friendly URLs if it is enabled and supported on your OpenCart website.

To uninstall the existing FBE plugin (version 3.1.2 and below), please follow the guide [here](https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/INSTALL_GUIDE.md#uninstall-the-plugin).

For installation of the latest FBE plugin (version 4.0.0 and above), please follow the guide [here](https://marketinsg.zendesk.com/hc/en-us/articles/360059899811-Facebook-for-OpenCart).

If you encounter any technical issues with the new FBE plugin, please feel free to reach out to us via our [help desk](https://marketinsg.zendesk.com/). 

Thank you!
