### ISSUE TITLE
Only few images got synced to facebook

### ISSUE THREAD

**Issue by miaosun** [facebookincubator/Facebook-For-OpenCart#87]
I am having problem with this extension in syncing the product from my opencart website to my facebook page. Have tried so many times (reinstalling the extension, reconnecting facebook page etc), no matter what I do, it always fails in syncing the products' images. To be exact, everytime the extension can successfully sync all my 92 products to facebook catalogues and facebook page shop section, but in these 92 products, only 4 have product images, the others despite having all other information (product name, price, description, website link etc) and right number of images (all the images are empty in both catalogues and facebook shop). I have verified that all the product images in my website share the same property (jpg format, 1200x1200 dimensions), can't figure out why everytime only 4 products (always the same 4) can get images synced. I have stuck in this for weeks, please help!

**Comment by shue249** [comment]
@miaosun Thank you for your feedback. We see that you have posted the question on OpenCart and on OpenCart support ticket. Let us continue the discussion here.

Can you share with me your webstore URL so that we can check on the status of the products.

**Comment by miaosun** [comment]
@shue249 Thank you for your reply. 
My opencart website: https://casadacortica.pt
Facebook shop page: https://facebook.com/casadacorticaportugal/shop

You can see that in the shop page only 4 products have images, tried lots of times and many ways, the current status is the best result I could get.

**Comment by miaosun** [comment]
Hi @shue249 Have you figured out anything?

**Comment by miaosun** [comment]
Hi @shue249 Sorry to bother you again, have you figured out anything?

**Comment by shue249** [comment]
@miaosun Apologies for the late reply.

We did a check on your catalog and found that the image url sent to FB is different from the one shown on your website. 
![image](https://user-images.githubusercontent.com/11957585/51319106-1f5bbb00-1a97-11e9-96e6-4bfdb57a48df.png)

Can I understand if you are using any 3rd party product management module to manage your inventory? This is because we are generating the image URL based on the default OpenCart product management module. The reason only 4 products have the image URL shown on Facebook is because their image is available on the default OpenCart product management module.

As a quick fix, I can suggest for you to edit the remaining other products to add in the product images and check if Facebook is now able to display the other images.

**Comment by miaosun** [comment]
@shue249 Thank you for your reply and information.

I don't think there is a 3rd party product management module in my website, I only use this extension https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=17 to import products from excel files. And by the way this is the theme used for the website: https://themeforest.net/item/up-multipurpose-responsive-opencart-theme/14484175.

Can you please tell me how exactly to perform the quick fix? Where should I change in your extension to make it send right url to FB?

Best regards.

**Comment by miaosun** [comment]
@shue249 Than you for your reply and information.

I have found the problem, the reason is because the folders and files in image/catalog were not having the right permissions, that's why the images were not accessible. I have fixed the permissions and now everything is working as expected. 

Thank you so much for the support and great extension. Best regards.
