### ISSUE TITLE
All products In Stock

### ISSUE THREAD

**Issue by slaventiy92** [facebookincubator/Facebook-For-OpenCart#90]
In opencart i have 5535 products in stock and 5173 products out of stock. But in facebook all products in stock

![2019-01-22_03-43-09](https://user-images.githubusercontent.com/13348534/51507400-7647f400-1df9-11e9-899d-d487edc327e4.png)
![2019-01-22_03-42-30](https://user-images.githubusercontent.com/13348534/51507401-7647f400-1df9-11e9-84b5-1804243436ff.png)

[facebook_ads_extension.log](https://github.com/facebookincubator/Facebook-For-OpenCart/files/2781011/facebook_ads_extension.log)

**Comment by shue249** [comment]
@slaventiy92 Thank you for the feedback.

For the Facebook out of stock status, if the product does not subtract stock, we are always setting the availability to be In Stock. Can you check the "subtract stock" status of your products.

![image](https://user-images.githubusercontent.com/11957585/51562453-d22b7f00-1ec4-11e9-8d4d-541bce2da8b9.png)

You can refer to the code logic here. If you want to ignore the logic to check for subtract stock, you can make the changes on this file your server directly.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L166-L172

**Comment by slaventiy92** [comment]
@shue249  all products have "Yes" in "Subtract stock"
![2019-01-23_15-40-58](https://user-images.githubusercontent.com/13348534/51610752-2dda2480-1f26-11e9-812b-f1d33696807c.png)

**Comment by shue249** [comment]
@slaventiy92 

Will you be able to do these:
1. Try to delete away the Facebook Ads Extension setting and complete the setup again
2. Check if those products still have the same problem, ie their quantity is zero and reflecting as in stock on Facebook
3. If point 2 is still true, can you share the store website URL so that we can verify deeper.

On our end, we have checked that the current logic for updating out of stock on Facebook is correct.

**Comment by shue249** [comment]
@slaventiy92 Wondering if there is any updates from your side that you can share with us for us to continue checking this.

**Comment by shue249** [comment]
@slaventiy92 We will proceed to close off this ticket, but pls feel free to reach to us if you have any further questions.

**Comment by AbdelReheem** [comment]
@shue249 Hello, I have the same issue from the day I update your amazing extension to Version: 2.1.10 and for your info I install and uninstall the module 5 times till the moment because of this issue and I'm trying to fix this from around a week as all the ads currently not running because of this.
Noting that I'm using OC 3.0.3.1

1- Instock and out of stock status was working fine on FB Plugin Version 2.1.8 
2- Once update to Version: 2.1.10 I found in Facebook catalog 1K units In stock which is wrong as I have only 430 Item in stock currently.
3- I'm not using the option for Not to subtract stock in Open Cart.
4- After 3 time of trial I completely uninstalled the module Version: 2.1.10 as follow A- Disable the Module from Extension B- Disable the module from Modification then Clear Modification C- Check database table is dropped D- Uninstall Extension Version: 2.1.10
5- After that I reinstalled your plugin Version: 2.1.8 and I got the correct stock fire and was having 430 item instock which is correct BUT didn't find any item in the page shop and I select it while installing and I can't find anyway to add and synchronize our catalog items to the page shop tab from 2 days now 

Now I'm Trapped and don't know what to do appreciate your help here as I didn't open new case as this case is for the same topic.

If you need our website and Facebook page and Catalog ID all are available upon your request

**Comment by shue249** [comment]
@AbdelReheem Thank you for the feedback. We have changed out logic for in stock & out of stock to be the same as OpenCart. Here is the logic.

  1. OpenCart quantity of (1 or more) = Facebook in stock
  2. OpenCart quantity of (0 or less), in stock = Facebook in stock
  3. OpenCart quantity of (0 or less), out of stock = Facebook out of stock
  4. OpenCart quantity of (0 or less), pre order = Facebook pre order
  5. OpenCart quantity of (0 or less), 2-3 days = Facebook in stock

If you are seeing stocks which should be out of stock but is still shown as in stock, that is probably due to the quantity value. You can fix this by changing those products quantity to zero.

**Comment by AbdelReheem** [comment]
@shue249 Thanks for your reply, Please read again my explanation I'm not changing anything in Opencart and I'm just changing your Module Version. In Another words I have 412 Item have quantity of more than zero and the rest of 828 item with quantity Zero 

On Facebook Catalog we was have 1K ( 1000 Item in Stock ) when using your Module Version 2.1.10
When we use your module version 2.1.8 we have accurate firing and 412 Instock item.

Anyway I have fixed this problem now as explained but still have the other issue of the page shop tab

As It's connected in the catalog setting but didn't find any item in the page shop and I select it while installing and I can't find anyway to add and synchronize our catalog items to the page shop tab. How to add and auto synchronize same catalog item to our Page shop tab !!

Please check the picture attached to be sure that there is something wrong in this module 
![Catalog setting](https://user-images.githubusercontent.com/47571934/59644553-ac519000-916d-11e9-92dd-085f73131090.jpg)
![Facebook_Catalog Items](https://user-images.githubusercontent.com/47571934/59644555-acea2680-916d-11e9-9490-ebe6e5ba3cad.jpg)
![OC Product Fetch_1218 Item](https://user-images.githubusercontent.com/47571934/59644558-acea2680-916d-11e9-9d9a-85c516420b76.jpg)
![Page shop tab](https://user-images.githubusercontent.com/47571934/59644559-acea2680-916d-11e9-8aa6-4ed4fc85f597.jpg)
![Website_439 Instock Item](https://user-images.githubusercontent.com/47571934/59644560-ad82bd00-916d-11e9-86d3-5a728b0bd6cf.jpg)




and I can't figure it out

**Comment by shue249** [comment]
@AbdelReheem 

Apologies for the delayed message. 

**On the topic of product out of stock status.**
Indeed, we have a change in logic for the product out of stock status from plugin version 2.1.8 to 2.1.9, hence you are seeing this change in implementation.

In 2.1.8, our logic for setting out of stock is based purely on the stock quantity and subtract stock option. The logic is as follow:
1 or more quantity => in stock on Facebook (regardless of subtract stock)
zero quantity, subtract stock = true => out of stock on Facebook
zero quantity, subtract stock = false => in stock on Facebook

In 2.1.9, we changed our logic so that it is consistent with OpenCart code and it is now based on stock quantity and out of stock status. The logic is as follow:
1 or more quantity => in stock on Facebook (regardless of out of stock status)
zero quantity, out of stock status = out of stock => out of stock on Facebook
zero quantity, out of stock status = in stock => in stock on Facebook
zero quantity, out of stock status = preorder => preorder on Facebook
zero quantity, out of stock status = 2-3 days => in stock on Facebook

You may want to check on the out of stock status for your products with zero quantity.

![image](https://user-images.githubusercontent.com/11957585/60405119-e0eb3000-9be0-11e9-955b-b0269ce8147d.png)

**On the topic of page shop not shown**
Have you enabled this option during the setup of Facebook Business Extension?
https://drive.google.com/open?id=1LqmQYAjuvgdsz6YTeRsIXTayIWYu_kQu

**Comment by AbdelReheem** [comment]
@shue249 Hello I know this discussion was from months, but I figured out just now why all product shown as instock in Facebook catalog and it's actually zero stock in our website.
There is something in opencart called localization and from the localization you can create new order status and new Stock status so we have multiple stock status created by us not in the default of opencart so we created Sold out stock status and we created Restocking Soon Stock status 

And most of the out of stock items have Restocking order sold out in the product Data Tab in out of stock status, So you set the module to read all of the customized localized new out of stock status like sold out and restocking in our case to be Instock 

to solve this you should add this feature in your logic so that it is consistent with OpenCart code and it is now based on stock quantity and out of stock status. The logic should be like this:

zero quantity, out of stock status = any new customized localized out of stock status => out of stock on Facebook

1 or more quantity => in stock on Facebook (regardless of out of stock status)
zero quantity, out of stock status = out of stock => out of stock on Facebook
zero quantity, out of stock status = in stock => in stock on Facebook
zero quantity, out of stock status = preorder => preorder on Facebook
zero quantity, out of stock status = 2-3 days => in stock on Facebook

I test it and opened on of the product which is sold out from our website and was shown as instock in Facebook and changed the out of stock status from Sold Out to Out of Stock and then it became out of stock in Facebook 

So appreciate if your adjust this in your module as it's too important for us or just guide me which file have the control of your out of stock logic to adjust it from my side

**Comment by shue249** [comment]
@AbdelReheem Thank you for the feedback. In version 2.1.10 of our plugin, we have updated our logic for out of stock status to be in sync with OpenCart. You can read more on the logic on our release notes here - https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/RELEASE#L24

However, we are only able to cater for OpenCart default stock status and is unable to handle custom out of stock status created by you. If you have developer resources, you can make the code changes on the file directly on your webserver. The code pointer is here https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookproductformatter.php#L174

Do note that if you make any code changes on your web server, subsequent installation of the newer version of the plugin will remove away those changes and you need to re-do the changes again.

**Comment by AbdelReheem** [comment]
@shue249 thanks for your reply appreciate it, But it was working very will with other custom out of stock status in your Version: 2.1.8 and Version: 2.1.9 and was firing custom OOS stutas as OOS on Facebook 

So if you can revert back this in the coming version as old version 2.1.8 will be much helpful for all users I think.

I'm the developer and owner of the website so I will try to fix it from my end in the mean while  

Thanks again for your support

**Comment by shue249** [comment]
@AbdelReheem Thank you for the feedback.

To be consistent with OpenCart's logic, we will be retaining the current logic of the current plugin. However, I can point you to the version 2.1.8 release and you can copied over the code logic for the stock availability into your current website on your opencart server. https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.8

Do note that if you upgrade the plugin to later versions in future, you will need to re-do this logic again.

**Comment by AbdelReheem** [comment]
@shue249 thanks for your usual support, I edit the logic of stocking in the current version 2.1.13 and it's working perfect now and synchronize all products with matching to actual website stock 

Thank you again for your great module and for your support
