### ISSUE TITLE
Facebook Ads Extension for Opencart 2.1.0.1 cant installed properly

### ISSUE THREAD

**Issue by Aykeagle** [facebookincubator/Facebook-For-OpenCart#96]
Hello,
I am trying to build up face ads extension to my opencart store but unfortunately this extension got some errors when i install it to extensions. I follow the steps from this link and also download the zip from here: https://www.facebook.com/business/help/opencart_pixel  
I think, i have done nothing wrong in installation because i can see the extension in the modifications section and also checked from the ftp for the permissions and the files but still extension doesnt work properly. I have attached some pics below and i am waiting for a prompt reply, thanks for help!!

![pic1](https://user-images.githubusercontent.com/47305863/52183312-b5257300-2817-11e9-9368-2fdb2a94f55a.png)

![pic2](https://user-images.githubusercontent.com/47305863/52183313-b5257300-2817-11e9-859d-8cbcbaea1b43.png)

**Comment by shue249** [comment]
@Aykeagle Thanks for your feedback.

Most probably the read+write permission on your server is not correct resulting in some files not copied over correctly. Can you check if you have given read+write recursively to the admin, catalog and system folders on your OpenCart server.

If this is done, pls proceed to remove the plugin and re-install the plugin again. We have a latest version, v2.1.3, which you can obtain from here https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.3

You can check if the files are correctly copied over by looking for these language files. The reason for the missing text is due to the missing language files.
![image](https://user-images.githubusercontent.com/11957585/52217033-9637e700-28d2-11e9-8cb4-ff0eb975972a.png)

**Comment by Aykeagle** [comment]
Thanks for the reply @shue249 ,
We have solved the problem, everything works fine now.
